/* ============================================================
   Dinner Decider — the pantry
   ------------------------------------------------------------
   Every dish is tagged against the eight questions so the
   matcher can score it. Field legend:

     n  name          o  origin (culture / country)
     e  emoji         b  one-line blurb
     u  utensils      ["hand","fork","spoon","chop"]
     m  mess          1 neat · 2 medium · 3 messy
     s  spice         subset of [0,1,2]  (0 none · 1 medium · 2 hot)
     f  fancy         subset of [1,2,3] (1 plastic tablecloths … 3 pinkies up)
     h  heavy on      subset of ["protein","veg","carbs"]
     a  appetite      subset of [1,2,3]  (1 light · 2 normal · 3 huge)
     w  weather       subset of ["cold","hot","mild"]
     d  diet          "omni" (contains meat/fish)
                      "veg"  (vegetarian: no meat, may have dairy/egg)
                      "vegan"(no animal products at all)
     k  basic         present and 1 when the dish is plain, familiar, American
                      home cooking — what the "I like toddler food" answer on
                      the fancy question pulls toward. Absent otherwise.
   ============================================================ */

const MEALS = [

  /* ───────────  UNITED STATES  ─────────── */
  { n:"Barbecue Baby Back Ribs", e:"🍖", o:"American South", b:"Sticky, smoky, and completely incompatible with a clean shirt.",
    u:["hand"], m:3, s:[0,1], f:[1,2], h:["protein"], a:[3], w:["mild","hot"], d:"omni" },
  { n:"Nashville Hot Chicken", e:"🔥", o:"Tennessee, USA", b:"Fried chicken dragged through cayenne paste. Bring milk.",
    u:["hand"], m:3, s:[2], f:[1,2], h:["protein"], a:[2,3], w:["mild","hot"], d:"omni" },
  { n:"Buffalo Wings", e:"🍗", o:"New York, USA", b:"Ten napkins minimum, and you'll still lick your fingers.",
    u:["hand"], m:3, s:[1,2], f:[1,2], h:["protein"], a:[2,3], w:["mild","cold"], d:"omni" },
  { n:"Classic Cheeseburger", e:"🍔", o:"United States", b:"The default answer that somehow never gets old.",
    u:["hand"], m:2, s:[0,1], f:[1,2], h:["protein"], a:[2,3], w:["mild","hot"], d:"omni", k:1 },
  { n:"Chicken and Waffles", e:"🧇", o:"American South", b:"Breakfast and dinner shake hands over a puddle of syrup.",
    u:["fork"], m:2, s:[0,1], f:[2], h:["carbs","protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"New England Clam Chowder", e:"🥣", o:"New England, USA", b:"A bowl of cream and shellfish built for a grey afternoon.",
    u:["spoon"], m:1, s:[0], f:[2,3], h:["protein"], a:[1,2], w:["cold"], d:"omni" },
  { n:"Sunday Pot Roast", e:"🍲", o:"United States", b:"Beef that gave up hours ago, surrounded by soft root vegetables.",
    u:["fork"], m:2, s:[0], f:[2,3], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Chicken Pot Pie", e:"🥧", o:"United States", b:"A crust over a stew. Weather-appropriate ninety percent of the year.",
    u:["fork"], m:2, s:[0], f:[2], h:["carbs","protein"], a:[2,3], w:["cold"], d:"omni", k:1 },
  { n:"Roast Turkey with All the Sides", e:"🦃", o:"United States", b:"You don't need a holiday. You just need an appetite.",
    u:["fork"], m:2, s:[0], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Meatloaf and Mashed Potatoes", e:"🥔", o:"United States", b:"Unglamorous, unfussy, and quietly excellent.",
    u:["fork"], m:2, s:[0], f:[2], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Shrimp and Grits", e:"🍤", o:"Lowcountry, USA", b:"Creamy corn, snappy shrimp, and a little bacon fat for courage.",
    u:["fork","spoon"], m:2, s:[1], f:[3], h:["protein","carbs"], a:[2], w:["cold","mild"], d:"omni" },
  { n:"Louisiana Gumbo", e:"🍲", o:"Louisiana, USA", b:"A dark roux, a long simmer, and a spoon that stands up in it.",
    u:["spoon"], m:2, s:[1,2], f:[2,3], h:["protein"], a:[2,3], w:["cold"], d:"omni" },
  { n:"Jambalaya", e:"🍚", o:"Louisiana, USA", b:"One pot, three meats, and rice that soaked up every bit of it.",
    u:["fork","spoon"], m:2, s:[1,2], f:[1,2], h:["carbs"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Lobster Roll", e:"🦞", o:"Maine, USA", b:"Cold lobster, warm bun, a boat you're not on but can imagine.",
    u:["hand"], m:2, s:[0], f:[2,3], h:["protein"], a:[1,2], w:["hot","mild"], d:"omni" },
  { n:"Baja Fish Tacos", e:"🌮", o:"California / Baja", b:"Crispy fish, shredded cabbage, and lime you squeeze yourself.",
    u:["hand"], m:2, s:[1], f:[1,2], h:["protein"], a:[2], w:["hot"], d:"omni" },
  { n:"Cobb Salad", e:"🥗", o:"California, USA", b:"A salad with enough bacon and egg to count as dinner.",
    u:["fork"], m:1, s:[0], f:[2,3], h:["protein","veg"], a:[1], w:["hot","mild"], d:"omni" },
  { n:"Grilled Ribeye with Chimichurri", e:"🥩", o:"American / Argentine", b:"A serious steak and a green sauce that cuts right through it.",
    u:["fork"], m:1, s:[0,1], f:[3], h:["protein"], a:[2,3], w:["mild","hot"], d:"omni" },
  { n:"Filet Mignon with Béarnaise", e:"🥩", o:"French-American", b:"Pinkies up. This is the one you order when someone else pays.",
    u:["fork"], m:1, s:[0], f:[3], h:["protein"], a:[2], w:["cold","mild"], d:"omni" },
  { n:"Pulled Pork Sandwich", e:"🐷", o:"Carolinas, USA", b:"It will fall apart. That is the entire point.",
    u:["hand"], m:3, s:[0,1], f:[1,2], h:["protein"], a:[3], w:["mild","hot"], d:"omni" },
  { n:"Texas Chili con Carne", e:"🌶️", o:"Texas, USA", b:"No beans, plenty of chiles, and a spoon doing all the work.",
    u:["spoon"], m:2, s:[1,2], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Buttermilk Fried Chicken", e:"🍗", o:"American South", b:"Eat it standing over the sink. Nobody's watching.",
    u:["hand"], m:3, s:[0,1], f:[1,2], h:["protein"], a:[3], w:["hot","mild"], d:"omni", k:1 },
  { n:"Philly Cheesesteak", e:"🥖", o:"Philadelphia, USA", b:"Griddled beef, melted cheese, and grease down your wrist.",
    u:["hand"], m:3, s:[0], f:[1], h:["protein","carbs"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Sloppy Joes", e:"🍔", o:"United States", b:"Named honestly. Wear something you already hate.",
    u:["hand"], m:3, s:[0,1], f:[1], h:["protein"], a:[2,3], w:["cold","mild"], d:"omni", k:1 },
  { n:"Turkey Club Sandwich", e:"🥪", o:"United States", b:"Neat, stacked, toothpicked. Somewhere to be, clearly.",
    u:["hand"], m:1, s:[0], f:[1,2], h:["protein"], a:[1,2], w:["mild","hot"], d:"omni", k:1 },
  { n:"Chicken Caesar Salad", e:"🥬", o:"American / Italian", b:"Crisp, sharp, and over before it makes a mess.",
    u:["fork"], m:1, s:[0], f:[2,3], h:["protein","veg"], a:[1], w:["hot","mild"], d:"omni" },
  { n:"Cedar Plank Salmon with Asparagus", e:"🐟", o:"Pacific Northwest, USA", b:"Clean, elegant, and done in twenty minutes.",
    u:["fork"], m:1, s:[0], f:[3], h:["protein"], a:[1,2], w:["mild","hot"], d:"omni" },
  { n:"Lowcountry Crab Boil", e:"🦀", o:"South Carolina, USA", b:"Dumped on newspaper. Cracked with your hands. Glorious chaos.",
    u:["hand"], m:3, s:[1,2], f:[1], h:["protein"], a:[3], w:["hot"], d:"omni" },
  { n:"Chicken Noodle Soup", e:"🍜", o:"United States", b:"The bowl you make when the weather wins.",
    u:["spoon"], m:1, s:[0], f:[1,2], h:["protein","carbs"], a:[1], w:["cold"], d:"omni", k:1 },
  { n:"Biscuits and Sausage Gravy", e:"🥐", o:"American South", b:"Breakfast for dinner, and a nap immediately after.",
    u:["fork"], m:2, s:[0,1], f:[1,2], h:["carbs"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Mac and Cheese", e:"🧀", o:"United States", b:"Carbs, cheese, and zero decisions left to make.",
    u:["fork"], m:2, s:[0], f:[1,2], h:["carbs"], a:[2,3], w:["cold"], d:"veg", k:1 },
  { n:"Grilled Cheese and Tomato Soup", e:"🥪", o:"United States", b:"The dunk is mandatory. So is the second half.",
    u:["hand","spoon"], m:2, s:[0], f:[1], h:["carbs"], a:[1,2], w:["cold"], d:"veg", k:1 },
  { n:"Corn Dogs and Fries", e:"🌭", o:"United States", b:"Paper plates. Mustard. No apologies whatsoever.",
    u:["hand"], m:2, s:[0], f:[1], h:["carbs","protein"], a:[2], w:["hot","mild"], d:"omni", k:1 },
  { n:"Loaded Nachos", e:"🧀", o:"Tex-Mex, USA", b:"A communal pile that ends in a fight over the last good chip.",
    u:["hand"], m:3, s:[1,2], f:[1], h:["carbs"], a:[2,3], w:["mild","hot"], d:"omni" },
  { n:"Chicago Deep-Dish Pizza", e:"🍕", o:"Chicago, USA", b:"A pizza that requires a knife, a fork, and a lie-down.",
    u:["fork"], m:2, s:[0], f:[1,2], h:["carbs"], a:[3], w:["cold"], d:"veg", k:1 },
  { n:"Clam Linguine", e:"🍝", o:"Italian-American", b:"White wine, garlic, and shells you pile on the side.",
    u:["fork"], m:2, s:[0,1], f:[3], h:["carbs","protein"], a:[2], w:["mild","hot"], d:"omni" },

  /* ───────────  MEXICO · CARIBBEAN · SOUTH AMERICA  ─────────── */
  { n:"Tacos al Pastor", e:"🌮", o:"Mexico", b:"Spit-roasted pork, pineapple, and three tortillas deep before you notice.",
    u:["hand"], m:2, s:[1,2], f:[1,2], h:["protein"], a:[2,3], w:["hot","mild"], d:"omni" },
  { n:"Birria Tacos with Consommé", e:"🌮", o:"Jalisco, Mexico", b:"You dunk it. It drips. That was always the deal.",
    u:["hand"], m:3, s:[1,2], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Enchiladas Verdes", e:"🫔", o:"Mexico", b:"Tomatillo sauce, melted cheese, and a fork that never stops.",
    u:["fork"], m:2, s:[1,2], f:[2], h:["protein"], a:[2,3], w:["cold","mild"], d:"omni" },
  { n:"Pozole Rojo", e:"🍲", o:"Mexico", b:"Hominy, chiles, and a bowl big enough to hide in.",
    u:["spoon"], m:2, s:[1,2], f:[2,3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Ceviche", e:"🐟", o:"Peru", b:"Raw fish cured in lime. Bright, cold, and gone in ten minutes.",
    u:["fork","spoon"], m:1, s:[1,2], f:[3], h:["protein"], a:[1], w:["hot"], d:"omni" },
  { n:"Tamales", e:"🫔", o:"Mexico", b:"Unwrap the husk. That's the whole ceremony.",
    u:["hand"], m:2, s:[0,1], f:[1,2], h:["carbs"], a:[2], w:["cold"], d:"omni" },
  { n:"Elote (Mexican Street Corn)", e:"🌽", o:"Mexico", b:"Mayo, cotija, chile, lime — and it ends up on your cheeks.",
    u:["hand"], m:3, s:[1], f:[1], h:["veg"], a:[1], w:["hot"], d:"veg" },
  { n:"Chiles Rellenos", e:"🌶️", o:"Mexico", b:"A whole poblano stuffed with cheese and fried into submission.",
    u:["fork"], m:2, s:[1], f:[2,3], h:["veg"], a:[2], w:["mild","cold"], d:"veg" },
  { n:"Sweet Potato and Black Bean Tacos", e:"🌮", o:"Mexican-inspired", b:"Roasted, smoky, and no animal was involved at any point.",
    u:["hand"], m:2, s:[1,2], f:[1,2], h:["veg"], a:[2], w:["hot","mild"], d:"vegan", k:1 },
  { n:"Feijoada", e:"🍛", o:"Brazil", b:"Black beans and every good cut of pork, over rice, all afternoon.",
    u:["spoon","fork"], m:2, s:[0,1], f:[2,3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Lomo Saltado", e:"🍟", o:"Peru", b:"Stir-fried beef with fries in the pan. Yes, in the pan.",
    u:["fork"], m:2, s:[1], f:[2,3], h:["protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Arepas con Queso", e:"🫓", o:"Venezuela / Colombia", b:"Griddled corn cakes split open and stuffed while hot.",
    u:["hand"], m:2, s:[0,1], f:[1,2], h:["carbs"], a:[2], w:["mild","hot"], d:"veg" },
  { n:"Cuban Sandwich", e:"🥖", o:"Cuba / Florida", b:"Pressed flat, cut on the diagonal, eaten far too fast.",
    u:["hand"], m:2, s:[0], f:[1,2], h:["protein","carbs"], a:[2], w:["hot","mild"], d:"omni" },
  { n:"Jerk Chicken", e:"🍗", o:"Jamaica", b:"Scotch bonnet, allspice, charcoal. It bites back.",
    u:["hand","fork"], m:2, s:[2], f:[1,2], h:["protein"], a:[2,3], w:["hot"], d:"omni" },
  { n:"Ropa Vieja with Rice", e:"🍛", o:"Cuba", b:"Shredded beef braised until it's basically a blanket.",
    u:["fork"], m:2, s:[0,1], f:[2,3], h:["protein"], a:[2,3], w:["cold","mild"], d:"omni" },
  { n:"Empanadas", e:"🥟", o:"Argentina", b:"A pocket of dinner you can eat while walking around.",
    u:["hand"], m:1, s:[0,1], f:[1,2], h:["carbs","protein"], a:[1,2], w:["mild","cold"], d:"omni" },

  /* ───────────  ITALY  ─────────── */
  { n:"Spaghetti and Meatballs", e:"🍝", o:"Italian-American", b:"Twirl badly, splash freely, enjoy completely.",
    u:["fork"], m:2, s:[0], f:[1,2], h:["carbs"], a:[2,3], w:["cold"], d:"omni", k:1 },
  { n:"Cacio e Pepe", e:"🧀", o:"Rome, Italy", b:"Three ingredients, one pan, absurdly good.",
    u:["fork"], m:2, s:[0,1], f:[2,3], h:["carbs"], a:[2], w:["cold","mild"], d:"veg" },
  { n:"Margherita Pizza", e:"🍕", o:"Naples, Italy", b:"Folded in half and eaten with your hands, like it's meant to be.",
    u:["hand"], m:2, s:[0], f:[1,2], h:["carbs"], a:[2,3], w:["mild","hot"], d:"veg", k:1 },
  { n:"Lasagna Bolognese", e:"🍲", o:"Emilia-Romagna, Italy", b:"Layers all the way down. A slice is never just a slice.",
    u:["fork"], m:2, s:[0], f:[2,3], h:["carbs"], a:[3], w:["cold"], d:"omni" },
  { n:"Wild Mushroom Risotto", e:"🍚", o:"Northern Italy", b:"Stirred for twenty minutes, silky, and worth every one of them.",
    u:["fork","spoon"], m:1, s:[0], f:[3], h:["carbs"], a:[2], w:["cold"], d:"veg" },
  { n:"Osso Buco alla Milanese", e:"🍖", o:"Milan, Italy", b:"Veal shank, saffron risotto, and a little spoon for the marrow.",
    u:["fork"], m:2, s:[0], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Chicken Parmesan", e:"🍗", o:"Italian-American", b:"Breaded, sauced, blanketed in cheese. Subtlety not included.",
    u:["fork"], m:2, s:[0], f:[2], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Minestrone", e:"🥣", o:"Italy", b:"Whatever's in the vegetable drawer, made dignified by broth.",
    u:["spoon"], m:1, s:[0], f:[1,2], h:["veg"], a:[1], w:["cold"], d:"vegan", k:1 },
  { n:"Caprese Salad", e:"🍅", o:"Capri, Italy", b:"Tomato, mozzarella, basil. Refuses to be improved.",
    u:["fork"], m:1, s:[0], f:[3], h:["veg"], a:[1], w:["hot"], d:"veg" },
  { n:"Spaghetti Carbonara", e:"🍝", o:"Rome, Italy", b:"Egg, cheese, guanciale, pepper. No cream, ever.",
    u:["fork"], m:2, s:[0,1], f:[2,3], h:["carbs"], a:[2,3], w:["cold"], d:"omni" },
  { n:"Arancini", e:"🍙", o:"Sicily, Italy", b:"Fried risotto balls you eat with your fingers, standing up.",
    u:["hand"], m:2, s:[0], f:[1,2], h:["carbs"], a:[1,2], w:["mild","cold"], d:"veg" },
  { n:"Eggplant Parmigiana", e:"🍆", o:"Southern Italy", b:"All the comfort of the chicken version, none of the chicken.",
    u:["fork"], m:2, s:[0], f:[2,3], h:["veg"], a:[3], w:["cold"], d:"veg", k:1 },
  { n:"Pasta Arrabbiata", e:"🌶️", o:"Rome, Italy", b:"Angry sauce. Garlic, chile, tomato, done in fifteen.",
    u:["fork"], m:2, s:[1,2], f:[1,2], h:["carbs"], a:[2], w:["cold","mild"], d:"vegan" },

  /* ───────────  FRANCE · SPAIN · GREECE  ─────────── */
  { n:"Beef Bourguignon", e:"🍷", o:"Burgundy, France", b:"Red wine, beef, and three hours you'll never regret.",
    u:["fork","spoon"], m:2, s:[0], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Coq au Vin", e:"🐓", o:"France", b:"Chicken braised into something far grander than chicken.",
    u:["fork"], m:2, s:[0], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"French Onion Soup", e:"🧅", o:"France", b:"A cheese lid over caramelized onions. The spoon fights for it.",
    u:["spoon"], m:2, s:[0], f:[2,3], h:["veg"], a:[1,2], w:["cold"], d:"veg" },
  { n:"Ratatouille", e:"🍆", o:"Provence, France", b:"Summer vegetables, olive oil, and patience.",
    u:["fork","spoon"], m:1, s:[0], f:[3], h:["veg"], a:[1], w:["hot","mild"], d:"vegan" },
  { n:"Croque Monsieur", e:"🥪", o:"France", b:"A grilled cheese that went to finishing school.",
    u:["fork"], m:2, s:[0], f:[2,3], h:["carbs"], a:[2], w:["cold"], d:"veg" },
  { n:"Moules Frites", e:"🦪", o:"France / Belgium", b:"Use an empty shell as tongs. Then drink the broth.",
    u:["hand","spoon"], m:3, s:[0,1], f:[3], h:["protein"], a:[2], w:["mild","cold"], d:"omni" },
  { n:"Bouillabaisse", e:"🐟", o:"Marseille, France", b:"A saffron seafood stew that takes itself very seriously.",
    u:["spoon"], m:2, s:[0,1], f:[3], h:["protein"], a:[2], w:["cold","mild"], d:"omni" },
  { n:"Beef Wellington", e:"🥩", o:"United Kingdom", b:"Pastry, mushroom duxelles, beef. The showpiece.",
    u:["fork"], m:1, s:[0], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Paella Valenciana", e:"🥘", o:"Valencia, Spain", b:"Saffron rice with a crust at the bottom worth fighting over.",
    u:["fork"], m:2, s:[0,1], f:[3], h:["carbs"], a:[3], w:["hot","mild"], d:"omni" },
  { n:"Patatas Bravas", e:"🥔", o:"Spain", b:"Fried potatoes under a spicy sauce, eaten with a toothpick or not.",
    u:["hand","fork"], m:2, s:[1,2], f:[1,2], h:["carbs"], a:[1], w:["hot","mild"], d:"vegan" },
  { n:"Gazpacho", e:"🍅", o:"Andalusia, Spain", b:"Cold soup for hot days. Absolutely no cooking involved.",
    u:["spoon"], m:1, s:[0,1], f:[3], h:["veg"], a:[1], w:["hot"], d:"vegan" },
  { n:"Tortilla Española", e:"🥚", o:"Spain", b:"Potato and egg, thick as a book, good at any temperature.",
    u:["fork"], m:1, s:[0], f:[2,3], h:["carbs"], a:[2], w:["mild","hot"], d:"veg" },
  { n:"Moussaka", e:"🍆", o:"Greece", b:"Eggplant, lamb, béchamel. Structurally magnificent.",
    u:["fork"], m:2, s:[0], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Chicken Souvlaki Pita", e:"🥙", o:"Greece", b:"Wrapped in foil, dripping tzatziki, eaten on the move.",
    u:["hand"], m:2, s:[0,1], f:[1,2], h:["protein"], a:[2], w:["hot"], d:"omni" },
  { n:"Greek Village Salad", e:"🥗", o:"Greece", b:"No lettuce. Just tomatoes, feta, and good olive oil.",
    u:["fork"], m:1, s:[0], f:[2,3], h:["veg"], a:[1], w:["hot"], d:"veg" },
  { n:"Spanakopita", e:"🥬", o:"Greece", b:"Spinach and feta between shattering layers of phyllo.",
    u:["hand","fork"], m:2, s:[0], f:[2,3], h:["veg","carbs"], a:[1,2], w:["mild","cold"], d:"veg" },

  /* ───────────  BRITISH ISLES · CENTRAL & EASTERN EUROPE  ─────────── */
  { n:"Fish and Chips", e:"🍟", o:"United Kingdom", b:"Vinegar, newspaper, and rain outside. The full experience.",
    u:["hand","fork"], m:2, s:[0], f:[1,2], h:["protein","carbs"], a:[3], w:["cold"], d:"omni" },
  { n:"Shepherd's Pie", e:"🥧", o:"United Kingdom / Ireland", b:"Lamb under a mashed potato roof. Dig in with a fork.",
    u:["fork"], m:2, s:[0], f:[2], h:["protein","carbs"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Bangers and Mash with Onion Gravy", e:"🌭", o:"United Kingdom", b:"Sausages, potato, gravy. A pub in food form.",
    u:["fork"], m:2, s:[0], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Steak and Ale Pie", e:"🥧", o:"United Kingdom", b:"A proper crust with beef and dark beer underneath.",
    u:["fork"], m:2, s:[0], f:[2,3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Irish Beef Stew", e:"🍲", o:"Ireland", b:"Barley, beef, and a spoon. Rain optional but recommended.",
    u:["spoon"], m:2, s:[0], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Wiener Schnitzel with Spätzle", e:"🍽️", o:"Austria / Germany", b:"Pounded thin, fried gold, squeezed with lemon.",
    u:["fork"], m:2, s:[0], f:[2,3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Swedish Meatballs", e:"🍛", o:"Sweden", b:"Cream gravy, lingonberry, and a quiet kind of joy.",
    u:["fork"], m:2, s:[0], f:[2,3], h:["protein"], a:[2,3], w:["cold"], d:"omni" },
  { n:"Pierogi with Caramelized Onions", e:"🥟", o:"Poland", b:"Potato dumplings pan-fried in butter until the edges crisp.",
    u:["fork"], m:2, s:[0], f:[1,2], h:["carbs"], a:[2,3], w:["cold"], d:"veg" },
  { n:"Hungarian Goulash", e:"🍲", o:"Hungary", b:"Paprika does the heavy lifting. So does the bread you dunk.",
    u:["spoon"], m:2, s:[1], f:[2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Borscht", e:"🥣", o:"Ukraine", b:"Beet-red, faintly sweet, and better on the second day.",
    u:["spoon"], m:1, s:[0], f:[2,3], h:["veg"], a:[1], w:["cold"], d:"vegan" },
  { n:"Cheese Fondue", e:"🫕", o:"Switzerland", b:"Spear the bread. Don't drop it. There are rules.",
    u:["hand"], m:2, s:[0], f:[3], h:["carbs"], a:[2], w:["cold"], d:"veg" },

  /* ───────────  MIDDLE EAST · NORTH AFRICA  ─────────── */
  { n:"Falafel Wrap with Tahini", e:"🥙", o:"Levant", b:"Crunchy chickpea fritters, pickles, and sauce down your arm.",
    u:["hand"], m:2, s:[1], f:[1,2], h:["protein"], a:[2], w:["hot","mild"], d:"vegan" },
  { n:"Chicken Shawarma Plate", e:"🍢", o:"Levant", b:"Shaved off the spit, piled on rice, garlic sauce everywhere.",
    u:["fork"], m:2, s:[1], f:[2], h:["protein"], a:[3], w:["mild","hot"], d:"omni" },
  { n:"Mezze Spread with Hummus and Pita", e:"🫓", o:"Levant", b:"A table of small plates and everyone reaching across it.",
    u:["hand"], m:2, s:[0,1], f:[2,3], h:["veg"], a:[1,2], w:["hot"], d:"vegan" },
  { n:"Lamb Shish Kebab", e:"🍢", o:"Turkey", b:"Charred off the skewer with grilled peppers and flatbread.",
    u:["hand","fork"], m:2, s:[0,1], f:[2,3], h:["protein"], a:[2,3], w:["hot","mild"], d:"omni" },
  { n:"Lamb Tagine with Apricots", e:"🍲", o:"Morocco", b:"Sweet, savory, slow, and served under a conical hat.",
    u:["fork","spoon"], m:2, s:[1], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Vegetable Couscous Tagine", e:"🥕", o:"Morocco", b:"Seven vegetables over fluffy couscous, warm with ras el hanout.",
    u:["fork","spoon"], m:2, s:[1], f:[3], h:["veg"], a:[2], w:["cold","mild"], d:"vegan" },
  { n:"Shakshuka", e:"🍳", o:"North Africa / Levant", b:"Eggs poached in spiced tomato, bread doing the scooping.",
    u:["spoon","hand"], m:2, s:[1,2], f:[1,2], h:["protein"], a:[2], w:["cold"], d:"veg" },
  { n:"Mujadara", e:"🍚", o:"Levant", b:"Lentils, rice, and a mountain of fried onions. Humble and perfect.",
    u:["fork","spoon"], m:1, s:[0,1], f:[1,2], h:["carbs"], a:[2], w:["cold","mild"], d:"vegan" },
  { n:"Koshari", e:"🍛", o:"Egypt", b:"Rice, lentils, pasta, chickpeas, crispy onions, hot sauce. All of it.",
    u:["fork","spoon"], m:2, s:[1,2], f:[1,2], h:["carbs"], a:[3], w:["cold","mild"], d:"vegan" },
  { n:"Fesenjan (Pomegranate Walnut Stew)", e:"🥘", o:"Iran", b:"Dark, tangy, nutty, and unlike anything else on the table.",
    u:["fork","spoon"], m:2, s:[0,1], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },

  /* ───────────  SUB-SAHARAN AFRICA  ─────────── */
  { n:"Jollof Rice with Grilled Chicken", e:"🍚", o:"Nigeria / Ghana", b:"Smoky tomato rice worth every argument about who makes it best.",
    u:["fork","spoon"], m:2, s:[1,2], f:[2], h:["carbs"], a:[3], w:["hot","mild"], d:"omni" },
  { n:"Doro Wat with Injera", e:"🍗", o:"Ethiopia", b:"Berbere-red chicken stew you scoop with spongy flatbread. No cutlery.",
    u:["hand"], m:3, s:[2], f:[2,3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Ethiopian Vegetable Combo", e:"🫓", o:"Ethiopia", b:"Lentils, greens, and shiro on injera — tear, scoop, repeat.",
    u:["hand"], m:3, s:[1,2], f:[2,3], h:["veg"], a:[2,3], w:["cold","mild"], d:"vegan" },
  { n:"Suya Skewers", e:"🍢", o:"Nigeria", b:"Peanut-chile crusted beef off a charcoal grill. Napkins are theoretical.",
    u:["hand"], m:2, s:[2], f:[1,2], h:["protein"], a:[2], w:["hot"], d:"omni" },
  { n:"West African Peanut Stew", e:"🥜", o:"West Africa", b:"Groundnut, tomato, sweet potato — thick enough to hold a spoon up.",
    u:["spoon"], m:2, s:[1,2], f:[1,2], h:["veg","protein"], a:[3], w:["cold"], d:"vegan" },
  { n:"Thieboudienne", e:"🐟", o:"Senegal", b:"Fish and broken rice cooked in one pot, the national dish for good reason.",
    u:["fork","spoon"], m:2, s:[1], f:[2], h:["carbs","protein"], a:[3], w:["mild","hot"], d:"omni" },
  { n:"Egusi Soup with Pounded Yam", e:"🥣", o:"Nigeria", b:"Melon-seed stew, eaten with your right hand. Gloriously messy.",
    u:["hand"], m:3, s:[2], f:[2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Bobotie", e:"🍛", o:"South Africa", b:"Curried mince under a savory custard, with chutney on the side.",
    u:["fork"], m:2, s:[1], f:[2,3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Chakalaka with Pap", e:"🌽", o:"South Africa", b:"Spicy vegetable relish over maize porridge. Cheap, hot, brilliant.",
    u:["spoon","fork"], m:2, s:[2], f:[1], h:["veg","carbs"], a:[2], w:["mild","cold"], d:"vegan" },

  /* ───────────  SOUTH ASIA  ─────────── */
  { n:"Butter Chicken with Naan", e:"🍛", o:"India", b:"Tomato, cream, and bread you use as a spoon.",
    u:["hand","fork"], m:2, s:[1], f:[2,3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Lamb Vindaloo", e:"🌶️", o:"Goa, India", b:"Vinegar and chiles in a fight. You are the venue.",
    u:["fork","spoon"], m:2, s:[2], f:[2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Chicken Biryani", e:"🍚", o:"India / Pakistan", b:"Layered, saffroned, and lifted from the pot like treasure.",
    u:["fork","spoon"], m:2, s:[1,2], f:[2,3], h:["carbs"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Tandoori Chicken", e:"🍗", o:"Punjab, India", b:"Yogurt-marinated, blistered in a hot oven, eaten off the bone.",
    u:["hand"], m:2, s:[1], f:[2,3], h:["protein"], a:[2], w:["hot","mild"], d:"omni" },
  { n:"Chana Masala with Rice", e:"🍛", o:"India", b:"Chickpeas in a spiced tomato gravy. Weeknight hero.",
    u:["fork","spoon"], m:2, s:[1,2], f:[1,2], h:["protein","veg"], a:[2], w:["cold","mild"], d:"vegan" },
  { n:"Palak Paneer", e:"🥬", o:"North India", b:"Creamed spinach with cheese cubes that squeak a little.",
    u:["fork","spoon"], m:2, s:[1], f:[2,3], h:["veg"], a:[2], w:["cold"], d:"veg" },
  { n:"Masala Dosa", e:"🫓", o:"South India", b:"A crisp metre-long crepe around spiced potato. Hands only.",
    u:["hand"], m:2, s:[1], f:[1,2], h:["carbs"], a:[2], w:["mild","hot"], d:"vegan" },
  { n:"Dal Tadka with Rice", e:"🥣", o:"India", b:"Lentils, ghee-fried spices, done. The definition of light and warm.",
    u:["spoon"], m:1, s:[1], f:[1,2], h:["protein"], a:[1], w:["cold"], d:"veg" },
  { n:"Aloo Gobi", e:"🥔", o:"India", b:"Potato and cauliflower, turmeric-yellow, dry-fried and simple.",
    u:["fork","spoon"], m:1, s:[1], f:[1,2], h:["veg"], a:[1,2], w:["mild","cold"], d:"vegan" },
  { n:"Samosa Chaat", e:"🥟", o:"India", b:"Smashed samosas, chutneys, yogurt, chaos. Eat immediately.",
    u:["hand","spoon"], m:3, s:[1,2], f:[1], h:["carbs"], a:[1,2], w:["mild","hot"], d:"veg" },
  { n:"Baingan Bharta", e:"🍆", o:"India", b:"Smoke-roasted eggplant mashed with tomato and green chile.",
    u:["fork","spoon"], m:2, s:[1,2], f:[2], h:["veg"], a:[2], w:["cold","mild"], d:"vegan" },

  /* ───────────  EAST ASIA  ─────────── */
  { n:"Tonkotsu Ramen", e:"🍜", o:"Japan", b:"Slurp loudly. The broth will end up on your chin regardless.",
    u:["chop","spoon"], m:3, s:[0,1], f:[1,2], h:["carbs"], a:[3], w:["cold"], d:"omni" },
  { n:"Nigiri Sushi Platter", e:"🍣", o:"Japan", b:"Cold, precise, and over before you've made a single crumb.",
    u:["chop"], m:1, s:[0,1], f:[3], h:["protein"], a:[1,2], w:["hot","mild"], d:"omni" },
  { n:"Chirashi Bowl", e:"🍱", o:"Japan", b:"Sashimi scattered over vinegared rice. Lunch's fancy cousin.",
    u:["chop"], m:1, s:[0,1], f:[3], h:["protein"], a:[2], w:["hot","mild"], d:"omni" },
  { n:"Chicken Katsu Curry", e:"🍛", o:"Japan", b:"Crunchy cutlet, thick brown curry, rice. Undefeated.",
    u:["chop","fork","spoon"], m:2, s:[1], f:[1,2], h:["carbs"], a:[3], w:["cold"], d:"omni" },
  { n:"Grilled Salmon Teishoku", e:"🐟", o:"Japan", b:"Fish, rice, miso, pickles. Balanced to an almost annoying degree.",
    u:["chop"], m:1, s:[0], f:[3], h:["protein"], a:[1,2], w:["mild","hot"], d:"omni" },
  { n:"Gyoza", e:"🥟", o:"Japan", b:"Crisp on one side, soft on the other, gone in four bites.",
    u:["chop"], m:1, s:[0,1], f:[1,2], h:["protein"], a:[1], w:["mild","cold"], d:"omni" },
  { n:"Kitsune Udon", e:"🍜", o:"Japan", b:"Fat noodles, clear broth, sweet fried tofu on top.",
    u:["chop","spoon"], m:2, s:[0], f:[1,2], h:["carbs"], a:[1,2], w:["cold"], d:"veg" },
  { n:"Vegetable Tempura", e:"🍤", o:"Japan", b:"Lacy, weightless, dipped in broth. Impossibly neat for fried food.",
    u:["chop"], m:1, s:[0], f:[3], h:["veg"], a:[1], w:["mild","hot"], d:"vegan" },
  { n:"Bibimbap", e:"🍲", o:"Korea", b:"Stir it all together in the hot stone bowl. That's the fun part.",
    u:["spoon","chop"], m:2, s:[1,2], f:[2,3], h:["veg"], a:[2], w:["cold","mild"], d:"veg" },
  { n:"Korean BBQ Bulgogi Ssam", e:"🥬", o:"Korea", b:"Grill it, wrap it in lettuce, eat it in one go. Sauce will escape.",
    u:["hand","chop"], m:3, s:[1,2], f:[2,3], h:["protein"], a:[3], w:["mild","cold"], d:"omni" },
  { n:"Tteokbokki", e:"🌶️", o:"Korea", b:"Chewy rice cakes in a red sauce that does not negotiate.",
    u:["chop"], m:2, s:[2], f:[1], h:["carbs"], a:[1,2], w:["cold"], d:"veg" },
  { n:"Kimchi Jjigae", e:"🍲", o:"Korea", b:"Sour, spicy, bubbling. The cure for a bad day and cold weather.",
    u:["spoon"], m:2, s:[2], f:[1,2], h:["protein"], a:[2], w:["cold"], d:"omni" },
  { n:"Japchae", e:"🍝", o:"Korea", b:"Glass noodles, sesame, vegetables. Light but never boring.",
    u:["chop"], m:1, s:[0,1], f:[2,3], h:["carbs","veg"], a:[1,2], w:["mild","hot"], d:"vegan" },
  { n:"Xiao Long Bao (Soup Dumplings)", e:"🥟", o:"Shanghai, China", b:"Bite too early and the soup goes down your shirt. Every time.",
    u:["chop"], m:3, s:[0,1], f:[2,3], h:["protein"], a:[1,2], w:["cold"], d:"omni" },
  { n:"Mapo Tofu", e:"🌶️", o:"Sichuan, China", b:"Numbing peppercorn, chile bean paste, silky tofu. Serious heat.",
    u:["chop","spoon"], m:2, s:[2], f:[1,2], h:["protein"], a:[2], w:["cold"], d:"omni" },
  { n:"Vegan Mapo Tofu", e:"🌶️", o:"Sichuan, China", b:"Mushrooms instead of pork, and the peppercorns don't care.",
    u:["chop","spoon"], m:2, s:[2], f:[1,2], h:["protein"], a:[2], w:["cold"], d:"vegan" },
  { n:"Kung Pao Chicken", e:"🥜", o:"Sichuan, China", b:"Peanuts, dried chiles, and a wok that was extremely hot.",
    u:["chop"], m:2, s:[1,2], f:[1,2], h:["protein"], a:[2], w:["cold","mild"], d:"omni" },
  { n:"Dan Dan Noodles", e:"🍜", o:"Sichuan, China", b:"Toss from the bottom. Sesame, chile oil, and a red-stained bowl.",
    u:["chop"], m:2, s:[2], f:[1,2], h:["carbs"], a:[2], w:["cold"], d:"omni" },
  { n:"Peking Duck Pancakes", e:"🦆", o:"Beijing, China", b:"Lacquered skin, thin pancakes, and a little ceremony at the table.",
    u:["hand"], m:2, s:[0], f:[3], h:["protein"], a:[2], w:["cold","mild"], d:"omni" },
  { n:"Char Siu Rice Plate", e:"🍚", o:"Cantonese, China", b:"Glossy barbecue pork over rice, with greens to feel virtuous.",
    u:["chop","fork"], m:2, s:[0], f:[1,2], h:["protein"], a:[3], w:["mild","cold"], d:"omni" },
  { n:"Congee with Scallions", e:"🥣", o:"China", b:"Rice porridge. Gentle, warm, and asks nothing of you.",
    u:["spoon"], m:1, s:[0], f:[1,2], h:["carbs"], a:[1], w:["cold"], d:"vegan" },
  { n:"Stir-Fried Garlic Bok Choy with Tofu", e:"🥬", o:"China", b:"Fifteen minutes, one wok, no regrets.",
    u:["chop"], m:1, s:[0,1], f:[1,2], h:["veg","protein"], a:[1], w:["hot","mild"], d:"vegan" },

  /* ───────────  SOUTHEAST ASIA  ─────────── */
  { n:"Pad Thai", e:"🍤", o:"Thailand", b:"Tamarind, peanuts, lime. The gateway noodle.",
    u:["chop","fork"], m:2, s:[1], f:[1,2], h:["carbs"], a:[2], w:["hot","mild"], d:"omni" },
  { n:"Green Curry with Jasmine Rice", e:"🍛", o:"Thailand", b:"Coconut milk softens the blow. Slightly.",
    u:["spoon","fork"], m:2, s:[2], f:[2,3], h:["veg","protein"], a:[2], w:["cold","mild"], d:"vegan" },
  { n:"Tom Yum Goong", e:"🍤", o:"Thailand", b:"Sour, hot, fragrant. Clears your sinuses and your mood.",
    u:["spoon"], m:1, s:[2], f:[2,3], h:["protein"], a:[1], w:["cold","mild"], d:"omni" },
  { n:"Massaman Curry", e:"🥘", o:"Thailand", b:"Potatoes, peanuts, warm spices. The gentle curry.",
    u:["spoon","fork"], m:2, s:[1], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Tofu Larb", e:"🌿", o:"Laos / Thailand", b:"Herby, limey, fiery, wrapped in lettuce leaves.",
    u:["hand","spoon"], m:2, s:[2], f:[2], h:["protein","veg"], a:[1], w:["hot"], d:"vegan" },
  { n:"Phở Bò", e:"🍜", o:"Vietnam", b:"Broth simmered overnight, noodles, herbs you add yourself.",
    u:["chop","spoon"], m:3, s:[0,1], f:[1,2], h:["carbs"], a:[2,3], w:["cold"], d:"omni" },
  { n:"Vegetable Phở", e:"🍜", o:"Vietnam", b:"Star anise and charred ginger doing all the heavy lifting.",
    u:["chop","spoon"], m:3, s:[0,1], f:[1,2], h:["carbs"], a:[2], w:["cold"], d:"vegan" },
  { n:"Bánh Mì", e:"🥖", o:"Vietnam", b:"A crackly baguette, pickles, cilantro, chile. Crumbs everywhere.",
    u:["hand"], m:2, s:[1], f:[1,2], h:["protein","carbs"], a:[2], w:["hot","mild"], d:"omni" },
  { n:"Vietnamese Summer Rolls", e:"🌯", o:"Vietnam", b:"Cold, translucent, dipped in peanut sauce. Neat as it gets.",
    u:["hand"], m:1, s:[0,1], f:[2,3], h:["veg"], a:[1], w:["hot"], d:"vegan" },
  { n:"Nasi Goreng", e:"🍳", o:"Indonesia", b:"Fried rice with a fried egg on top, because of course.",
    u:["fork","spoon"], m:2, s:[1,2], f:[1,2], h:["carbs"], a:[2], w:["hot","mild"], d:"omni" },
  { n:"Chicken Adobo", e:"🍗", o:"Philippines", b:"Vinegar, soy, garlic, bay. Three ingredients, endless depth.",
    u:["spoon","fork"], m:2, s:[0,1], f:[1,2], h:["protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Hainanese Chicken Rice", e:"🍚", o:"Singapore / Hainan", b:"Poached chicken, fragrant rice, three sauces. Deceptively simple.",
    u:["chop","spoon"], m:1, s:[0,1], f:[2,3], h:["protein"], a:[2], w:["hot","mild"], d:"omni" },
  { n:"Laksa", e:"🍜", o:"Malaysia / Singapore", b:"Coconut curry noodle soup that splashes and doesn't apologize.",
    u:["chop","spoon"], m:3, s:[2], f:[1,2], h:["carbs"], a:[3], w:["cold"], d:"omni" },

  /* ───────────  PLANT-FORWARD EVERYWHERE ELSE  ─────────── */
  { n:"Mushroom Wellington", e:"🍄", o:"British-inspired, vegan", b:"Puff pastry and mushroom duxelles. The centerpiece, minus the beef.",
    u:["fork"], m:1, s:[0], f:[3], h:["protein","veg"], a:[3], w:["cold"], d:"vegan" },
  { n:"Roasted Cauliflower Steak", e:"🥦", o:"Modern vegetarian", b:"Charred edges, tahini drizzle, and a knife you barely need.",
    u:["fork"], m:1, s:[0,1], f:[3], h:["veg"], a:[1], w:["mild","cold"], d:"vegan" },
  { n:"Black Bean Burger", e:"🍔", o:"American vegan", b:"Holds together, tastes great, and yes it's actually a burger.",
    u:["hand"], m:2, s:[1], f:[1,2], h:["protein"], a:[2], w:["mild","hot"], d:"vegan", k:1 },
  { n:"Vegan Chili", e:"🌶️", o:"American vegan", b:"Three beans, chipotle, and a pot that feeds you twice.",
    u:["spoon"], m:2, s:[1,2], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"vegan", k:1 },
  { n:"Lentil Shepherd's Pie", e:"🥧", o:"British vegan", b:"Same mashed potato roof, entirely different foundation.",
    u:["fork"], m:2, s:[0], f:[2], h:["protein","carbs"], a:[3], w:["cold"], d:"vegan", k:1 },
  { n:"Butternut Squash Soup", e:"🎃", o:"Modern vegan", b:"Velvety, sweet, and blitzed smooth. Bowl, blanket, done.",
    u:["spoon"], m:1, s:[0,1], f:[2,3], h:["veg"], a:[1], w:["cold"], d:"vegan", k:1 },
  { n:"Buddha Bowl with Tahini", e:"🥗", o:"Modern vegan", b:"Grains, roasted vegetables, chickpeas, sauce. Assembled, not cooked.",
    u:["fork"], m:1, s:[0,1], f:[2], h:["veg"], a:[2], w:["hot","mild"], d:"vegan" },
  { n:"Vegan Poke Bowl", e:"🥑", o:"Hawaii, vegan", b:"Marinated watermelon or tofu over cold rice. Summer in a bowl.",
    u:["chop","fork"], m:1, s:[0,1], f:[2,3], h:["veg"], a:[1,2], w:["hot"], d:"vegan" },
  { n:"Vegan Ramen", e:"🍜", o:"Japan, vegan", b:"Miso-mushroom broth with corn and chile oil. Slurp away.",
    u:["chop","spoon"], m:3, s:[1,2], f:[1,2], h:["carbs"], a:[3], w:["cold"], d:"vegan" },
  { n:"Stuffed Bell Peppers", e:"🫑", o:"Mediterranean vegetarian", b:"Rice, herbs, and whatever else needed using up.",
    u:["fork"], m:2, s:[0,1], f:[2], h:["veg"], a:[2], w:["cold","mild"], d:"vegan", k:1 },
  { n:"Watermelon and Feta Salad", e:"🍉", o:"Mediterranean", b:"Cold, salty, sweet. The only sensible answer in a heatwave.",
    u:["fork"], m:1, s:[0], f:[3], h:["veg"], a:[1], w:["hot"], d:"veg" },
  { n:"Veggie Sushi Rolls", e:"🍙", o:"Japan, vegan", b:"Avocado, cucumber, pickled radish. Tidy little cylinders.",
    u:["chop"], m:1, s:[0,1], f:[2,3], h:["veg"], a:[1], w:["hot","mild"], d:"vegan" },
  { n:"Sheet-Pan Gnocchi and Tomatoes", e:"🍅", o:"Modern Italian", b:"One tray, blistered tomatoes, crisp gnocchi. Minimal washing up.",
    u:["fork"], m:2, s:[0,1], f:[1,2], h:["carbs"], a:[2,3], w:["cold","mild"], d:"vegan", k:1 },
  { n:"Vegan Bánh Mì", e:"🥖", o:"Vietnam, vegan", b:"Lemongrass tofu, pickled carrot, and a baguette that shatters.",
    u:["hand"], m:2, s:[1,2], f:[1,2], h:["protein","carbs"], a:[2], w:["hot","mild"], d:"vegan" },
  { n:"Vegan Jackfruit Tacos", e:"🌮", o:"Mexican-inspired vegan", b:"Pulled, saucy, and dripping the way pulled anything should.",
    u:["hand"], m:3, s:[1,2], f:[1,2], h:["veg"], a:[2], w:["hot","mild"], d:"vegan" },
  { n:"Chilled Cucumber Avocado Soup", e:"🥒", o:"Modern vegan", b:"No stove involved. Just a blender and a hot afternoon.",
    u:["spoon"], m:1, s:[0], f:[3], h:["veg"], a:[1], w:["hot"], d:"vegan" },
  { n:"Vegan Pad See Ew", e:"🍜", o:"Thailand, vegan", b:"Wide noodles, charred greens, dark soy. Wok smoke included.",
    u:["chop","fork"], m:2, s:[0,1], f:[1,2], h:["carbs"], a:[2,3], w:["mild","cold"], d:"vegan" },
  { n:"Vegan Ethiopian Shiro Wat", e:"🥣", o:"Ethiopia, vegan", b:"Chickpea flour stew, spiced deep red, scooped with injera.",
    u:["hand","spoon"], m:3, s:[2], f:[1,2], h:["protein"], a:[2], w:["cold"], d:"vegan" },
  { n:"Truffle Tagliatelle", e:"🍝", o:"Piedmont, Italy", b:"Butter, cheese, and shaved truffle. Pinkies up, obviously.",
    u:["fork"], m:2, s:[0], f:[3], h:["carbs"], a:[2], w:["cold","mild"], d:"veg" },
  { n:"Vegan Mushroom Risotto", e:"🍄", o:"Italy, vegan", b:"Olive oil instead of butter, and nobody at the table notices.",
    u:["fork","spoon"], m:1, s:[0], f:[3], h:["carbs"], a:[2], w:["cold"], d:"vegan" },
  { n:"Falafel Mezze Platter", e:"🧆", o:"Levant, vegan", b:"Hummus, baba ganoush, pickles, warm pita. Grazing at its finest.",
    u:["hand"], m:2, s:[1], f:[3], h:["protein"], a:[2,3], w:["hot","mild"], d:"vegan" },
  { n:"Vegan Sushi Temaki Cones", e:"🍥", o:"Japan, vegan", b:"Hand rolls you assemble yourself and eat immediately.",
    u:["hand"], m:2, s:[0,1], f:[2,3], h:["veg"], a:[1,2], w:["hot"], d:"vegan" },

  /* ───────────  ALLRECIPES MOST-POPULAR MAINS  ─────────── */
  { n:"Marry Me Chicken", e:"🍗", o:"American, viral", b:"Sun-dried tomato cream sauce, one pan, thirty minutes.",
    u:["fork"], m:2, s:[0,1], f:[2], h:["protein"], a:[2,3], w:["cold","mild"], d:"omni", k:1 },
  { n:"Beef Stroganoff", e:"🍄", o:"Russian-American", b:"Sour cream, mushrooms, and egg noodles underneath it all.",
    u:["fork"], m:2, s:[0], f:[2], h:["protein","carbs"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Baked Ziti", e:"🧀", o:"Italian-American", b:"Ricotta, mozzarella, and the crispy bits at the edge of the dish.",
    u:["fork"], m:2, s:[0], f:[1,2], h:["carbs"], a:[3], w:["cold"], d:"veg", k:1 },
  { n:"Broccoli Cheddar Soup", e:"🥦", o:"United States", b:"Thick, orange, and best in a hollowed-out bread bowl.",
    u:["spoon"], m:1, s:[0], f:[1,2], h:["veg"], a:[1,2], w:["cold"], d:"veg", k:1 },
  { n:"Zuppa Toscana", e:"🥣", o:"Italian-American", b:"Sausage, kale, potatoes, cream. The restaurant copycat everyone makes.",
    u:["spoon"], m:2, s:[1], f:[1,2], h:["protein"], a:[2,3], w:["cold"], d:"omni", k:1 },
  { n:"Chicken and Dumplings", e:"🍲", o:"American South", b:"Soft dumplings dropped into broth. Pure cold-weather insulation.",
    u:["spoon","fork"], m:2, s:[0], f:[1,2], h:["protein","carbs"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Shrimp Scampi", e:"🍤", o:"Italian-American", b:"Garlic, butter, white wine, lemon. Twenty minutes, start to finish.",
    u:["fork"], m:2, s:[0,1], f:[2,3], h:["protein","carbs"], a:[2], w:["mild","hot"], d:"omni" },
  { n:"Beef and Broccoli", e:"🥦", o:"Chinese-American", b:"Better than takeout, and you already have the soy sauce.",
    u:["chop","fork"], m:2, s:[0,1], f:[1,2], h:["protein"], a:[2,3], w:["cold","mild"], d:"omni" },
  { n:"General Tso's Chicken", e:"🍗", o:"Chinese-American", b:"Sweet, sticky, faintly fiery, and unapologetically not authentic.",
    u:["chop","fork"], m:2, s:[1,2], f:[1,2], h:["protein"], a:[2,3], w:["cold","mild"], d:"omni" },
  { n:"Fettuccine Alfredo", e:"🍝", o:"Italian-American", b:"Butter, cream, parmesan. No further questions.",
    u:["fork"], m:2, s:[0], f:[2], h:["carbs"], a:[3], w:["cold"], d:"veg", k:1 },
  { n:"Salisbury Steak", e:"🍖", o:"United States", b:"Beef patties drowned in onion gravy. Diner food, done at home.",
    u:["fork"], m:2, s:[0], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Tuna Noodle Casserole", e:"🐟", o:"United States", b:"Pantry ingredients, crushed chips on top, zero pretense.",
    u:["fork"], m:2, s:[0], f:[1], h:["carbs"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Slow Cooker Chicken Taco Soup", e:"🌶️", o:"Tex-Mex", b:"Dump everything in at breakfast, eat it at dinner.",
    u:["spoon"], m:2, s:[1,2], f:[1], h:["protein"], a:[2,3], w:["cold"], d:"omni", k:1 },
  { n:"Egg Roll in a Bowl", e:"🥬", o:"American, low-carb", b:"All the filling, none of the wrapper. Done in fifteen minutes.",
    u:["fork","chop"], m:1, s:[0,1], f:[1,2], h:["protein","veg"], a:[1,2], w:["cold","mild"], d:"omni" },
  { n:"Chicken Fried Steak", e:"🍳", o:"Texas, USA", b:"Battered, fried, and buried under peppery white gravy.",
    u:["fork"], m:2, s:[0,1], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"American Goulash", e:"🍝", o:"United States", b:"Elbow macaroni, ground beef, tomato. Feeds a crowd for nothing.",
    u:["spoon","fork"], m:2, s:[0,1], f:[1], h:["carbs"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Sheet-Pan Chicken Fajitas", e:"🫓", o:"Tex-Mex", b:"Peppers, onions, one tray, and tortillas you fill yourself.",
    u:["hand"], m:2, s:[1], f:[1,2], h:["protein"], a:[2,3], w:["hot","mild"], d:"omni" },

  /* ───────────  NYT COOKING MOST-POPULAR MAINS  ─────────── */
  { n:"Buttermilk-Brined Roast Chicken", e:"🍗", o:"NYT Cooking", b:"Brined overnight, roasted hot. The one everybody saves.",
    u:["fork","hand"], m:2, s:[0], f:[2,3], h:["protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Momofuku Bo Ssam", e:"🥬", o:"Korean-American", b:"Slow-roasted pork shoulder, lettuce leaves, and a very messy table.",
    u:["hand"], m:3, s:[1,2], f:[2,3], h:["protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Lemony Shrimp and Bean Stew", e:"🍤", o:"NYT Cooking", b:"Pantry beans, quick shrimp, a lot of lemon. Thirty minutes.",
    u:["spoon"], m:1, s:[0,1], f:[2], h:["protein"], a:[1,2], w:["cold","mild"], d:"omni" },
  { n:"Vietnamese Garlic Noodles", e:"🍜", o:"San Francisco / Vietnam", b:"An indecent amount of garlic and butter. That's the recipe.",
    u:["chop","fork"], m:2, s:[0,1], f:[1,2], h:["carbs"], a:[2,3], w:["cold","mild"], d:"omni" },
  { n:"Mississippi Roast", e:"🍖", o:"American South", b:"Chuck roast, pepperoncini, butter. Five ingredients, no effort.",
    u:["fork"], m:2, s:[0,1], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Peruvian Roast Chicken with Green Sauce", e:"🍗", o:"Peru", b:"Charred, cumin-rubbed, and served with a fiercely green sauce.",
    u:["hand","fork"], m:2, s:[1,2], f:[2], h:["protein"], a:[3], w:["mild","hot"], d:"omni" },
  { n:"Spiced Chickpea Stew with Coconut and Turmeric", e:"🥣", o:"NYT Cooking", b:"Golden, creamy, and famous enough to have its own hashtag.",
    u:["spoon"], m:2, s:[1], f:[2], h:["protein","veg"], a:[2], w:["cold"], d:"vegan" },
  { n:"Caramelized Shallot Pasta", e:"🧅", o:"NYT Cooking", b:"Shallots cooked far longer than feels reasonable. Worth it.",
    u:["fork"], m:2, s:[1], f:[2,3], h:["carbs"], a:[2], w:["cold","mild"], d:"omni" },
  { n:"Pasta alla Vodka", e:"🍝", o:"Italian-American", b:"Tomato, cream, a splash of vodka, and shockingly good results.",
    u:["fork"], m:2, s:[0,1], f:[2], h:["carbs"], a:[2,3], w:["cold"], d:"veg" },
  { n:"Chicken Marbella", e:"🫒", o:"Silver Palate / NYT", b:"Prunes, olives and capers. Dinner-party food since 1979.",
    u:["fork"], m:2, s:[0], f:[3], h:["protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Red Lentil Soup with Lemon", e:"🍋", o:"NYT Cooking", b:"Cumin, lemon, and thirty minutes between you and dinner.",
    u:["spoon"], m:1, s:[1], f:[2], h:["protein"], a:[1], w:["cold"], d:"vegan" },
  { n:"Cold Sesame Noodles", e:"🥜", o:"NYT Cooking", b:"Sesame paste, chile oil, scallions. Better straight from the fridge.",
    u:["chop","fork"], m:2, s:[0,1], f:[1,2], h:["carbs"], a:[2], w:["hot"], d:"vegan" },
  { n:"Gochujang Buttered Noodles", e:"🌶️", o:"NYT Cooking", b:"Five ingredients, ten minutes, and a genuinely serious kick.",
    u:["chop","fork"], m:2, s:[2], f:[1,2], h:["carbs"], a:[2], w:["cold"], d:"veg" },
  { n:"Miso-Butter Salmon", e:"🐟", o:"NYT Cooking", b:"Sweet, salty, caramelized under the broiler in ten minutes.",
    u:["fork","chop"], m:1, s:[0], f:[3], h:["protein"], a:[2], w:["cold","mild"], d:"omni" },
  { n:"Chicken Piccata", e:"🍋", o:"Italian-American", b:"Lemon, capers, butter. Elegant on a weeknight budget.",
    u:["fork"], m:1, s:[0], f:[3], h:["protein"], a:[2], w:["mild","cold"], d:"omni" },
  { n:"Red Wine Braised Short Ribs", e:"🍖", o:"NYT Cooking", b:"Three hours in the oven and the fork does the carving.",
    u:["fork"], m:2, s:[0], f:[3], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Baked Feta Pasta", e:"🧀", o:"Viral / NYT Cooking", b:"A block of feta, a tray of tomatoes, and one stir at the end.",
    u:["fork"], m:2, s:[0,1], f:[2], h:["carbs"], a:[2,3], w:["cold","mild"], d:"veg" },
  { n:"Mushroom Bourguignon", e:"🍄", o:"Smitten Kitchen", b:"All the red-wine depth of the beef version, none of the beef.",
    u:["fork","spoon"], m:2, s:[0], f:[2,3], h:["veg","protein"], a:[3], w:["cold"], d:"vegan" },
  { n:"Chicken Paprikash", e:"🥘", o:"Hungary", b:"Sweet paprika, sour cream, and buttered noodles to catch it.",
    u:["fork","spoon"], m:2, s:[1], f:[2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Kimchi Fried Rice", e:"🍚", o:"Korea", b:"Old rice, older kimchi, a fried egg on top. Peak refrigerator cooking.",
    u:["spoon","chop"], m:2, s:[1,2], f:[1,2], h:["carbs"], a:[2], w:["cold","mild"], d:"omni" },
  { n:"Chicken Tikka Masala", e:"🍛", o:"British-Indian", b:"Charred chicken in a spiced tomato cream. The nation's favourite.",
    u:["fork","spoon"], m:2, s:[1,2], f:[2], h:["protein"], a:[3], w:["cold"], d:"omni" },

  /* ───────────  SMITTEN KITCHEN MAINS  ─────────── */
  { n:"Pizza Beans", e:"🫘", o:"Smitten Kitchen", b:"Beans, greens and molten mozzarella. The internet's favourite bean pot.",
    u:["spoon","fork"], m:2, s:[0,1], f:[1,2], h:["protein","veg"], a:[2,3], w:["cold"], d:"veg" },
  { n:"Zucchini Butter Spaghetti", e:"🥒", o:"Smitten Kitchen", b:"Zucchini cooked down to a jammy butter. Three ingredients, no sauce.",
    u:["fork"], m:2, s:[0], f:[2], h:["carbs"], a:[2], w:["hot","mild"], d:"veg" },
  { n:"Baked Orzo with Eggplant and Mozzarella", e:"🍆", o:"Smitten Kitchen", b:"Pasta that behaves like a casserole, with a browned cheese lid.",
    u:["fork"], m:2, s:[0], f:[2], h:["carbs"], a:[3], w:["cold"], d:"veg" },
  { n:"Chicken with Forty Cloves of Garlic", e:"🧄", o:"Smitten Kitchen", b:"Forty. The cloves go sweet and spreadable, and nobody complains.",
    u:["fork"], m:2, s:[0], f:[3], h:["protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Spinach and Cheese Strata", e:"🥬", o:"Smitten Kitchen", b:"Custardy bread pudding gone savoury. Assembles the night before.",
    u:["fork"], m:2, s:[0], f:[2], h:["carbs"], a:[2,3], w:["cold"], d:"veg" },
  { n:"Tomato and Corn Pie", e:"🌽", o:"Smitten Kitchen", b:"August in a pie tin, under a biscuit crust.",
    u:["fork"], m:2, s:[0], f:[2], h:["veg"], a:[2], w:["hot"], d:"veg" },
  { n:"Charred Cauliflower Quesadillas", e:"🫓", o:"Smitten Kitchen", b:"Blistered cauliflower and cheese, folded and griddled.",
    u:["hand"], m:2, s:[1], f:[1,2], h:["veg"], a:[2], w:["mild","hot"], d:"veg" },
  { n:"Broccoli Parmesan Fritters", e:"🥦", o:"Smitten Kitchen", b:"Crisp-edged, cheesy, and gone before they reach the table.",
    u:["hand","fork"], m:2, s:[0], f:[1,2], h:["veg"], a:[1,2], w:["mild","cold"], d:"veg" },
  { n:"Butternut Squash and Caramelized Onion Galette", e:"🎃", o:"Smitten Kitchen", b:"A free-form tart with a rye crust. Deliberately uneven, entirely the point.",
    u:["fork","hand"], m:2, s:[0], f:[3], h:["veg"], a:[2], w:["cold"], d:"veg" },
  { n:"Sheet Pan Chicken Tikka", e:"🍗", o:"Smitten Kitchen", b:"Yogurt-marinated chicken over cauliflower and potatoes. One tray.",
    u:["fork"], m:2, s:[1,2], f:[2], h:["protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Smoky Sheet Pan Chicken with Cauliflower", e:"🔥", o:"Smitten Kitchen", b:"Smoked paprika, one pan, and almost nothing to wash up.",
    u:["fork"], m:2, s:[1], f:[2], h:["protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Spaghetti Carbonara Pie", e:"🍝", o:"Smitten Kitchen", b:"Carbonara baked until it slices. Yes, slices.",
    u:["fork"], m:2, s:[0], f:[2], h:["carbs"], a:[3], w:["cold"], d:"omni" },
  { n:"Burst Tomato Galette with Corn and Zucchini", e:"🍅", o:"Smitten Kitchen", b:"Summer vegetables collapsed into a craggy free-form tart.",
    u:["fork"], m:2, s:[0], f:[3], h:["veg"], a:[2], w:["hot"], d:"veg" },
  { n:"Broccoli Melts", e:"🥪", o:"Smitten Kitchen", b:"Garlicky broccoli mashed onto toast under cheese. Dinner in fifteen.",
    u:["hand"], m:2, s:[0,1], f:[1,2], h:["veg"], a:[1,2], w:["mild","cold"], d:"veg" },
  { n:"Miso Maple Ribs", e:"🍖", o:"Smitten Kitchen", b:"Sticky, salty-sweet, and eaten entirely with your hands.",
    u:["hand"], m:3, s:[0,1], f:[2,3], h:["protein"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Everyday Meatballs", e:"🍝", o:"Smitten Kitchen", b:"Simmered straight in the sauce, no browning step, no fuss.",
    u:["fork"], m:2, s:[0], f:[2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Lentil Soup with Sausage", e:"🥣", o:"Smitten Kitchen", b:"Smoky sausage, soft lentils, and a pot that improves overnight.",
    u:["spoon"], m:1, s:[0,1], f:[1,2], h:["protein"], a:[2,3], w:["cold"], d:"omni" },
  { n:"Chicken Milanese", e:"🍗", o:"Smitten Kitchen", b:"Pounded thin, fried crisp, buried under a lemony pile of greens.",
    u:["fork"], m:1, s:[0], f:[3], h:["protein"], a:[2,3], w:["mild","hot"], d:"omni" },
  { n:"Corn Chowder", e:"🌽", o:"Smitten Kitchen", b:"Sweet corn, potatoes, and a broth made from the stripped cobs.",
    u:["spoon"], m:1, s:[0], f:[2], h:["veg"], a:[1,2], w:["mild","cold"], d:"veg" },
  { n:"Leek Fritters", e:"🧅", o:"Smitten Kitchen", b:"Soft inside, lacy outside, with a garlicky yogurt to dunk them in.",
    u:["hand","fork"], m:2, s:[0], f:[2], h:["veg"], a:[1], w:["mild","cold"], d:"veg" },
  { n:"Winter Squash Pasta Bake", e:"🎃", o:"Smitten Kitchen", b:"Squash puréed into the sauce so nobody notices the vegetables.",
    u:["fork"], m:2, s:[0], f:[2], h:["carbs"], a:[3], w:["cold"], d:"veg" },

  /* ───────────  EVERYDAY AMERICAN STANDARDS  ─────────── */
  { n:"Grilled Hot Dogs", e:"🌭", o:"United States", b:"Bun, mustard, done. Nobody has ever needed a recipe.",
    u:["hand"], m:2, s:[0], f:[1], h:["protein","carbs"], a:[2], w:["hot","mild"], d:"omni", k:1 },
  { n:"BLT Sandwich", e:"🥓", o:"United States", b:"Bacon, lettuce, tomato, too much mayonnaise. Peak August.",
    u:["hand"], m:2, s:[0], f:[1,2], h:["protein"], a:[2], w:["hot","mild"], d:"omni", k:1 },
  { n:"Reuben Sandwich", e:"🥪", o:"United States", b:"Corned beef, kraut, Russian dressing, griddled until it leaks.",
    u:["hand"], m:3, s:[0], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"French Dip Sandwich", e:"🥖", o:"California, USA", b:"Roast beef on a roll with a cup of jus for dunking.",
    u:["hand"], m:3, s:[0], f:[2], h:["protein"], a:[3], w:["cold"], d:"omni" },
  { n:"Meatball Sub", e:"🍝", o:"Italian-American", b:"Sauce down your wrist within two bites. Accept it.",
    u:["hand"], m:3, s:[0], f:[1], h:["protein","carbs"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Italian Sub", e:"🥖", o:"Italian-American", b:"Cold cuts, provolone, oil and vinegar, shredded lettuce.",
    u:["hand"], m:2, s:[0,1], f:[1], h:["protein"], a:[2,3], w:["hot","mild"], d:"omni" },
  { n:"Tuna Melt", e:"🧀", o:"United States", b:"Diner food at its most unpretentious, and better for it.",
    u:["hand"], m:2, s:[0], f:[1], h:["protein"], a:[2], w:["cold","mild"], d:"omni", k:1 },
  { n:"Chicken Salad Sandwich", e:"🥪", o:"United States", b:"Celery, mayo, soft bread. Lunch that wandered into dinner.",
    u:["hand"], m:1, s:[0], f:[1,2], h:["protein"], a:[1,2], w:["hot","mild"], d:"omni", k:1 },
  { n:"Patty Melt", e:"🍔", o:"United States", b:"A burger and a grilled cheese, on rye, with griddled onions.",
    u:["hand"], m:3, s:[0], f:[1], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Turkey Burger", e:"🍔", o:"United States", b:"The lighter burger, which is still very much a burger.",
    u:["hand"], m:2, s:[0,1], f:[1,2], h:["protein"], a:[2], w:["mild","hot"], d:"omni", k:1 },
  { n:"Shrimp Po' Boy", e:"🍤", o:"Louisiana, USA", b:"Fried shrimp, remoulade, dressed. Lean forward over the plate.",
    u:["hand"], m:3, s:[1], f:[1,2], h:["protein"], a:[3], w:["hot","mild"], d:"omni" },
  { n:"Hard-Shell Beef Tacos", e:"🌮", o:"Tex-Mex", b:"The shell shatters on the first bite. It always does.",
    u:["hand"], m:3, s:[1], f:[1], h:["protein"], a:[2], w:["mild","hot"], d:"omni", k:1 },
  { n:"Chicken Burrito Bowl", e:"🥗", o:"Tex-Mex", b:"Rice, beans, salsa, everything in one bowl and no wrapping.",
    u:["fork"], m:1, s:[1,2], f:[1,2], h:["protein"], a:[2], w:["hot","mild"], d:"omni" },
  { n:"Chicken Quesadilla", e:"🫓", o:"Tex-Mex", b:"Griddled, cut in wedges, dipped in sour cream.",
    u:["hand"], m:2, s:[0,1], f:[1], h:["protein"], a:[2], w:["mild","hot"], d:"omni", k:1 },
  { n:"Bean and Cheese Burrito", e:"🌯", o:"Tex-Mex", b:"Cheap, filling, and better wrapped in foil.",
    u:["hand"], m:2, s:[0,1], f:[1], h:["carbs"], a:[2], w:["mild","hot"], d:"veg", k:1 },
  { n:"Cheese Enchiladas", e:"🧀", o:"Tex-Mex", b:"Red chile gravy poured over the top and baked until bubbling.",
    u:["fork"], m:2, s:[1], f:[1,2], h:["carbs"], a:[2,3], w:["cold","mild"], d:"veg", k:1 },
  { n:"Beef Enchilada Casserole", e:"🍲", o:"Tex-Mex", b:"Layered rather than rolled, because nobody has that kind of time.",
    u:["fork"], m:2, s:[1], f:[1,2], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Orange Chicken", e:"🍊", o:"Chinese-American", b:"Sweet, sticky, crisp. The takeout order you always end up making.",
    u:["fork","chop"], m:2, s:[0,1], f:[1,2], h:["protein"], a:[2,3], w:["cold","mild"], d:"omni" },
  { n:"Beef Lo Mein", e:"🍜", o:"Chinese-American", b:"Soft noodles, soy, and vegetables you can pick around.",
    u:["chop","fork"], m:2, s:[0,1], f:[1,2], h:["carbs"], a:[2,3], w:["cold","mild"], d:"omni", k:1 },
  { n:"Chicken Fried Rice", e:"🍚", o:"Chinese-American", b:"Day-old rice, a hot pan, and whatever is in the fridge.",
    u:["fork","chop"], m:2, s:[0], f:[1,2], h:["carbs"], a:[2], w:["mild","cold"], d:"omni", k:1 },
  { n:"Sweet and Sour Pork", e:"🍍", o:"Chinese-American", b:"Bright red sauce, pineapple, and no apologies for either.",
    u:["chop","fork"], m:2, s:[0], f:[1,2], h:["protein"], a:[2,3], w:["mild","cold"], d:"omni" },
  { n:"Teriyaki Chicken Bowl", e:"🍱", o:"Japanese-American", b:"Glazed chicken over rice with broccoli. Weeknight autopilot.",
    u:["chop","fork"], m:1, s:[0], f:[1,2], h:["protein"], a:[2], w:["mild","hot"], d:"omni" },
  { n:"Pepperoni Pizza", e:"🍕", o:"United States", b:"The default order. Grease pooling in the cups is the good part.",
    u:["hand"], m:2, s:[0,1], f:[1,2], h:["carbs"], a:[2,3], w:["mild","cold"], d:"omni", k:1 },
  { n:"Chicken Tenders and Fries", e:"🍟", o:"United States", b:"Order it at thirty-five. Nobody is keeping score.",
    u:["hand"], m:2, s:[0], f:[1], h:["protein"], a:[2,3], w:["mild","hot"], d:"omni", k:1 },
  { n:"Chicken Cordon Bleu", e:"🍗", o:"American / Swiss", b:"Ham and cheese rolled inside chicken, breaded, and baked.",
    u:["fork"], m:2, s:[0], f:[2,3], h:["protein"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Pork Chops with Applesauce", e:"🍎", o:"United States", b:"Pan-seared, and the applesauce is not optional.",
    u:["fork"], m:1, s:[0], f:[2], h:["protein"], a:[2,3], w:["mild","cold"], d:"omni", k:1 },
  { n:"Texas Brisket", e:"🥩", o:"Texas, USA", b:"Twelve hours of smoke, a black bark, and white bread on the side.",
    u:["hand","fork"], m:3, s:[0,1], f:[1,2], h:["protein"], a:[3], w:["mild","hot"], d:"omni" },
  { n:"Crab Cakes", e:"🦀", o:"Maryland, USA", b:"Mostly crab, barely any filler, browned in butter.",
    u:["fork"], m:1, s:[0,1], f:[3], h:["protein"], a:[2], w:["hot","mild"], d:"omni" },
  { n:"Sausage and Peppers", e:"🫑", o:"Italian-American", b:"One skillet, sweet peppers, and a roll if you want one.",
    u:["fork"], m:2, s:[1], f:[1,2], h:["protein"], a:[3], w:["mild","cold"], d:"omni", k:1 },
  { n:"Chicken and Rice Casserole", e:"🍚", o:"United States", b:"The dish that shows up when somebody has a new baby.",
    u:["fork"], m:2, s:[0], f:[1,2], h:["carbs"], a:[3], w:["cold"], d:"omni", k:1 },
  { n:"Red Beans and Rice", e:"🍚", o:"Louisiana, USA", b:"Monday dinner in New Orleans, smoky with andouille.",
    u:["spoon","fork"], m:2, s:[1], f:[1,2], h:["carbs"], a:[3], w:["cold","mild"], d:"omni" },
  { n:"Stuffed Shells", e:"🐚", o:"Italian-American", b:"Ricotta piped into pasta, blanketed in sauce and mozzarella.",
    u:["fork"], m:2, s:[0], f:[2], h:["carbs"], a:[3], w:["cold"], d:"veg", k:1 },
  { n:"Loaded Baked Potato", e:"🥔", o:"United States", b:"Butter, sour cream, cheese, chives. A potato doing far too much.",
    u:["fork"], m:2, s:[0], f:[1,2], h:["carbs"], a:[2], w:["cold"], d:"veg", k:1 },
  { n:"Pasta Primavera", e:"🥦", o:"Italian-American", b:"Spring vegetables, a light cream sauce, and a lot of parmesan.",
    u:["fork"], m:2, s:[0], f:[2], h:["veg","carbs"], a:[2], w:["hot","mild"], d:"veg", k:1 },
  { n:"Chef Salad", e:"🥗", o:"United States", b:"Ham, turkey, egg and cheese in neat rows over lettuce.",
    u:["fork"], m:1, s:[0], f:[2], h:["protein","veg"], a:[1], w:["hot","mild"], d:"omni" },
];
