//
//  Meals.swift
//  What should I eat for dinner?
//
//  GENERATED from js/meals.js — do not edit by hand.
//  Regenerate with: node scripts/gen-swift-meals.js
//
//  272 dishes, each tagged against all eight questions.
//

import Foundation

enum MealDatabase {

    /// Every dish the matcher can choose from.
    static let all: [Meal] = {
        var meals: [Meal] = []
        meals.reserveCapacity(272)
        meals.append(contentsOf: part1())
        meals.append(contentsOf: part2())
        meals.append(contentsOf: part3())
        meals.append(contentsOf: part4())
        meals.append(contentsOf: part5())
        meals.append(contentsOf: part6())
        meals.append(contentsOf: part7())
        return meals
    }()

    private static func part1() -> [Meal] {
        [
        Meal("Barbecue Baby Back Ribs", "🍖", "American South", "Sticky, smoky, and completely incompatible with a clean shirt.",
             u: [.hand], m: 3, s: [0, 1], f: [1, 2], h: [.protein], a: [3], w: [.mild, .hot], d: .omnivore),
        Meal("Nashville Hot Chicken", "🔥", "Tennessee, USA", "Fried chicken dragged through cayenne paste. Bring milk.",
             u: [.hand], m: 3, s: [2], f: [1, 2], h: [.protein], a: [2, 3], w: [.mild, .hot], d: .omnivore),
        Meal("Buffalo Wings", "🍗", "New York, USA", "Ten napkins minimum, and you'll still lick your fingers.",
             u: [.hand], m: 3, s: [1, 2], f: [1, 2], h: [.protein], a: [2, 3], w: [.mild, .cold], d: .omnivore),
        Meal("Classic Cheeseburger", "🍔", "United States", "The default answer that somehow never gets old.",
             u: [.hand], m: 2, s: [0, 1], f: [1, 2], h: [.protein], a: [2, 3], w: [.mild, .hot], d: .omnivore, k: true),
        Meal("Chicken and Waffles", "🧇", "American South", "Breakfast and dinner shake hands over a puddle of syrup.",
             u: [.fork], m: 2, s: [0, 1], f: [2], h: [.carbs, .protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("New England Clam Chowder", "🥣", "New England, USA", "A bowl of cream and shellfish built for a grey afternoon.",
             u: [.spoon], m: 1, s: [0], f: [2, 3], h: [.protein], a: [1, 2], w: [.cold], d: .omnivore),
        Meal("Sunday Pot Roast", "🍲", "United States", "Beef that gave up hours ago, surrounded by soft root vegetables.",
             u: [.fork], m: 2, s: [0], f: [2, 3], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Chicken Pot Pie", "🥧", "United States", "A crust over a stew. Weather-appropriate ninety percent of the year.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.carbs, .protein], a: [2, 3], w: [.cold], d: .omnivore, k: true),
        Meal("Roast Turkey with All the Sides", "🦃", "United States", "You don't need a holiday. You just need an appetite.",
             u: [.fork], m: 2, s: [0], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Meatloaf and Mashed Potatoes", "🥔", "United States", "Unglamorous, unfussy, and quietly excellent.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Shrimp and Grits", "🍤", "Lowcountry, USA", "Creamy corn, snappy shrimp, and a little bacon fat for courage.",
             u: [.fork, .spoon], m: 2, s: [1], f: [3], h: [.protein, .carbs], a: [2], w: [.cold, .mild], d: .omnivore),
        Meal("Louisiana Gumbo", "🍲", "Louisiana, USA", "A dark roux, a long simmer, and a spoon that stands up in it.",
             u: [.spoon], m: 2, s: [1, 2], f: [2, 3], h: [.protein], a: [2, 3], w: [.cold], d: .omnivore),
        Meal("Jambalaya", "🍚", "Louisiana, USA", "One pot, three meats, and rice that soaked up every bit of it.",
             u: [.fork, .spoon], m: 2, s: [1, 2], f: [1, 2], h: [.carbs], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Lobster Roll", "🦞", "Maine, USA", "Cold lobster, warm bun, a boat you're not on but can imagine.",
             u: [.hand], m: 2, s: [0], f: [2, 3], h: [.protein], a: [1, 2], w: [.hot, .mild], d: .omnivore),
        Meal("Baja Fish Tacos", "🌮", "California / Baja", "Crispy fish, shredded cabbage, and lime you squeeze yourself.",
             u: [.hand], m: 2, s: [1], f: [1, 2], h: [.protein], a: [2], w: [.hot], d: .omnivore),
        Meal("Cobb Salad", "🥗", "California, USA", "A salad with enough bacon and egg to count as dinner.",
             u: [.fork], m: 1, s: [0], f: [2, 3], h: [.protein, .vegetable], a: [1], w: [.hot, .mild], d: .omnivore),
        Meal("Grilled Ribeye with Chimichurri", "🥩", "American / Argentine", "A serious steak and a green sauce that cuts right through it.",
             u: [.fork], m: 1, s: [0, 1], f: [3], h: [.protein], a: [2, 3], w: [.mild, .hot], d: .omnivore),
        Meal("Filet Mignon with Béarnaise", "🥩", "French-American", "Pinkies up. This is the one you order when someone else pays.",
             u: [.fork], m: 1, s: [0], f: [3], h: [.protein], a: [2], w: [.cold, .mild], d: .omnivore),
        Meal("Pulled Pork Sandwich", "🐷", "Carolinas, USA", "It will fall apart. That is the entire point.",
             u: [.hand], m: 3, s: [0, 1], f: [1, 2], h: [.protein], a: [3], w: [.mild, .hot], d: .omnivore),
        Meal("Texas Chili con Carne", "🌶️", "Texas, USA", "No beans, plenty of chiles, and a spoon doing all the work.",
             u: [.spoon], m: 2, s: [1, 2], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Buttermilk Fried Chicken", "🍗", "American South", "Eat it standing over the sink. Nobody's watching.",
             u: [.hand], m: 3, s: [0, 1], f: [1, 2], h: [.protein], a: [3], w: [.hot, .mild], d: .omnivore, k: true),
        Meal("Philly Cheesesteak", "🥖", "Philadelphia, USA", "Griddled beef, melted cheese, and grease down your wrist.",
             u: [.hand], m: 3, s: [0], f: [1], h: [.protein, .carbs], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Sloppy Joes", "🍔", "United States", "Named honestly. Wear something you already hate.",
             u: [.hand], m: 3, s: [0, 1], f: [1], h: [.protein], a: [2, 3], w: [.cold, .mild], d: .omnivore, k: true),
        Meal("Turkey Club Sandwich", "🥪", "United States", "Neat, stacked, toothpicked. Somewhere to be, clearly.",
             u: [.hand], m: 1, s: [0], f: [1, 2], h: [.protein], a: [1, 2], w: [.mild, .hot], d: .omnivore, k: true),
        Meal("Chicken Caesar Salad", "🥬", "American / Italian", "Crisp, sharp, and over before it makes a mess.",
             u: [.fork], m: 1, s: [0], f: [2, 3], h: [.protein, .vegetable], a: [1], w: [.hot, .mild], d: .omnivore),
        Meal("Cedar Plank Salmon with Asparagus", "🐟", "Pacific Northwest, USA", "Clean, elegant, and done in twenty minutes.",
             u: [.fork], m: 1, s: [0], f: [3], h: [.protein], a: [1, 2], w: [.mild, .hot], d: .omnivore),
        Meal("Lowcountry Crab Boil", "🦀", "South Carolina, USA", "Dumped on newspaper. Cracked with your hands. Glorious chaos.",
             u: [.hand], m: 3, s: [1, 2], f: [1], h: [.protein], a: [3], w: [.hot], d: .omnivore),
        Meal("Chicken Noodle Soup", "🍜", "United States", "The bowl you make when the weather wins.",
             u: [.spoon], m: 1, s: [0], f: [1, 2], h: [.protein, .carbs], a: [1], w: [.cold], d: .omnivore, k: true),
        Meal("Biscuits and Sausage Gravy", "🥐", "American South", "Breakfast for dinner, and a nap immediately after.",
             u: [.fork], m: 2, s: [0, 1], f: [1, 2], h: [.carbs], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Mac and Cheese", "🧀", "United States", "Carbs, cheese, and zero decisions left to make.",
             u: [.fork], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [2, 3], w: [.cold], d: .vegetarian, k: true),
        Meal("Grilled Cheese and Tomato Soup", "🥪", "United States", "The dunk is mandatory. So is the second half.",
             u: [.hand, .spoon], m: 2, s: [0], f: [1], h: [.carbs], a: [1, 2], w: [.cold], d: .vegetarian, k: true),
        Meal("Corn Dogs and Fries", "🌭", "United States", "Paper plates. Mustard. No apologies whatsoever.",
             u: [.hand], m: 2, s: [0], f: [1], h: [.carbs, .protein], a: [2], w: [.hot, .mild], d: .omnivore, k: true),
        Meal("Loaded Nachos", "🧀", "Tex-Mex, USA", "A communal pile that ends in a fight over the last good chip.",
             u: [.hand], m: 3, s: [1, 2], f: [1], h: [.carbs], a: [2, 3], w: [.mild, .hot], d: .omnivore),
        Meal("Chicago Deep-Dish Pizza", "🍕", "Chicago, USA", "A pizza that requires a knife, a fork, and a lie-down.",
             u: [.fork], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [3], w: [.cold], d: .vegetarian, k: true),
        Meal("Clam Linguine", "🍝", "Italian-American", "White wine, garlic, and shells you pile on the side.",
             u: [.fork], m: 2, s: [0, 1], f: [3], h: [.carbs, .protein], a: [2], w: [.mild, .hot], d: .omnivore),
        Meal("Tacos al Pastor", "🌮", "Mexico", "Spit-roasted pork, pineapple, and three tortillas deep before you notice.",
             u: [.hand], m: 2, s: [1, 2], f: [1, 2], h: [.protein], a: [2, 3], w: [.hot, .mild], d: .omnivore),
        Meal("Birria Tacos with Consommé", "🌮", "Jalisco, Mexico", "You dunk it. It drips. That was always the deal.",
             u: [.hand], m: 3, s: [1, 2], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Enchiladas Verdes", "🫔", "Mexico", "Tomatillo sauce, melted cheese, and a fork that never stops.",
             u: [.fork], m: 2, s: [1, 2], f: [2], h: [.protein], a: [2, 3], w: [.cold, .mild], d: .omnivore),
        Meal("Pozole Rojo", "🍲", "Mexico", "Hominy, chiles, and a bowl big enough to hide in.",
             u: [.spoon], m: 2, s: [1, 2], f: [2, 3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Ceviche", "🐟", "Peru", "Raw fish cured in lime. Bright, cold, and gone in ten minutes.",
             u: [.fork, .spoon], m: 1, s: [1, 2], f: [3], h: [.protein], a: [1], w: [.hot], d: .omnivore)
        ]
    }

    private static func part2() -> [Meal] {
        [
        Meal("Tamales", "🫔", "Mexico", "Unwrap the husk. That's the whole ceremony.",
             u: [.hand], m: 2, s: [0, 1], f: [1, 2], h: [.carbs], a: [2], w: [.cold], d: .omnivore),
        Meal("Elote (Mexican Street Corn)", "🌽", "Mexico", "Mayo, cotija, chile, lime — and it ends up on your cheeks.",
             u: [.hand], m: 3, s: [1], f: [1], h: [.vegetable], a: [1], w: [.hot], d: .vegetarian),
        Meal("Chiles Rellenos", "🌶️", "Mexico", "A whole poblano stuffed with cheese and fried into submission.",
             u: [.fork], m: 2, s: [1], f: [2, 3], h: [.vegetable], a: [2], w: [.mild, .cold], d: .vegetarian),
        Meal("Sweet Potato and Black Bean Tacos", "🌮", "Mexican-inspired", "Roasted, smoky, and no animal was involved at any point.",
             u: [.hand], m: 2, s: [1, 2], f: [1, 2], h: [.vegetable], a: [2], w: [.hot, .mild], d: .vegan, k: true),
        Meal("Feijoada", "🍛", "Brazil", "Black beans and every good cut of pork, over rice, all afternoon.",
             u: [.spoon, .fork], m: 2, s: [0, 1], f: [2, 3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Lomo Saltado", "🍟", "Peru", "Stir-fried beef with fries in the pan. Yes, in the pan.",
             u: [.fork], m: 2, s: [1], f: [2, 3], h: [.protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Arepas con Queso", "🫓", "Venezuela / Colombia", "Griddled corn cakes split open and stuffed while hot.",
             u: [.hand], m: 2, s: [0, 1], f: [1, 2], h: [.carbs], a: [2], w: [.mild, .hot], d: .vegetarian),
        Meal("Cuban Sandwich", "🥖", "Cuba / Florida", "Pressed flat, cut on the diagonal, eaten far too fast.",
             u: [.hand], m: 2, s: [0], f: [1, 2], h: [.protein, .carbs], a: [2], w: [.hot, .mild], d: .omnivore),
        Meal("Jerk Chicken", "🍗", "Jamaica", "Scotch bonnet, allspice, charcoal. It bites back.",
             u: [.hand, .fork], m: 2, s: [2], f: [1, 2], h: [.protein], a: [2, 3], w: [.hot], d: .omnivore),
        Meal("Ropa Vieja with Rice", "🍛", "Cuba", "Shredded beef braised until it's basically a blanket.",
             u: [.fork], m: 2, s: [0, 1], f: [2, 3], h: [.protein], a: [2, 3], w: [.cold, .mild], d: .omnivore),
        Meal("Empanadas", "🥟", "Argentina", "A pocket of dinner you can eat while walking around.",
             u: [.hand], m: 1, s: [0, 1], f: [1, 2], h: [.carbs, .protein], a: [1, 2], w: [.mild, .cold], d: .omnivore),
        Meal("Spaghetti and Meatballs", "🍝", "Italian-American", "Twirl badly, splash freely, enjoy completely.",
             u: [.fork], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [2, 3], w: [.cold], d: .omnivore, k: true),
        Meal("Cacio e Pepe", "🧀", "Rome, Italy", "Three ingredients, one pan, absurdly good.",
             u: [.fork], m: 2, s: [0, 1], f: [2, 3], h: [.carbs], a: [2], w: [.cold, .mild], d: .vegetarian),
        Meal("Margherita Pizza", "🍕", "Naples, Italy", "Folded in half and eaten with your hands, like it's meant to be.",
             u: [.hand], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [2, 3], w: [.mild, .hot], d: .vegetarian, k: true),
        Meal("Lasagna Bolognese", "🍲", "Emilia-Romagna, Italy", "Layers all the way down. A slice is never just a slice.",
             u: [.fork], m: 2, s: [0], f: [2, 3], h: [.carbs], a: [3], w: [.cold], d: .omnivore),
        Meal("Wild Mushroom Risotto", "🍚", "Northern Italy", "Stirred for twenty minutes, silky, and worth every one of them.",
             u: [.fork, .spoon], m: 1, s: [0], f: [3], h: [.carbs], a: [2], w: [.cold], d: .vegetarian),
        Meal("Osso Buco alla Milanese", "🍖", "Milan, Italy", "Veal shank, saffron risotto, and a little spoon for the marrow.",
             u: [.fork], m: 2, s: [0], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Chicken Parmesan", "🍗", "Italian-American", "Breaded, sauced, blanketed in cheese. Subtlety not included.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Minestrone", "🥣", "Italy", "Whatever's in the vegetable drawer, made dignified by broth.",
             u: [.spoon], m: 1, s: [0], f: [1, 2], h: [.vegetable], a: [1], w: [.cold], d: .vegan, k: true),
        Meal("Caprese Salad", "🍅", "Capri, Italy", "Tomato, mozzarella, basil. Refuses to be improved.",
             u: [.fork], m: 1, s: [0], f: [3], h: [.vegetable], a: [1], w: [.hot], d: .vegetarian),
        Meal("Spaghetti Carbonara", "🍝", "Rome, Italy", "Egg, cheese, guanciale, pepper. No cream, ever.",
             u: [.fork], m: 2, s: [0, 1], f: [2, 3], h: [.carbs], a: [2, 3], w: [.cold], d: .omnivore),
        Meal("Arancini", "🍙", "Sicily, Italy", "Fried risotto balls you eat with your fingers, standing up.",
             u: [.hand], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [1, 2], w: [.mild, .cold], d: .vegetarian),
        Meal("Eggplant Parmigiana", "🍆", "Southern Italy", "All the comfort of the chicken version, none of the chicken.",
             u: [.fork], m: 2, s: [0], f: [2, 3], h: [.vegetable], a: [3], w: [.cold], d: .vegetarian, k: true),
        Meal("Pasta Arrabbiata", "🌶️", "Rome, Italy", "Angry sauce. Garlic, chile, tomato, done in fifteen.",
             u: [.fork], m: 2, s: [1, 2], f: [1, 2], h: [.carbs], a: [2], w: [.cold, .mild], d: .vegan),
        Meal("Beef Bourguignon", "🍷", "Burgundy, France", "Red wine, beef, and three hours you'll never regret.",
             u: [.fork, .spoon], m: 2, s: [0], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Coq au Vin", "🐓", "France", "Chicken braised into something far grander than chicken.",
             u: [.fork], m: 2, s: [0], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("French Onion Soup", "🧅", "France", "A cheese lid over caramelized onions. The spoon fights for it.",
             u: [.spoon], m: 2, s: [0], f: [2, 3], h: [.vegetable], a: [1, 2], w: [.cold], d: .vegetarian),
        Meal("Ratatouille", "🍆", "Provence, France", "Summer vegetables, olive oil, and patience.",
             u: [.fork, .spoon], m: 1, s: [0], f: [3], h: [.vegetable], a: [1], w: [.hot, .mild], d: .vegan),
        Meal("Croque Monsieur", "🥪", "France", "A grilled cheese that went to finishing school.",
             u: [.fork], m: 2, s: [0], f: [2, 3], h: [.carbs], a: [2], w: [.cold], d: .vegetarian),
        Meal("Moules Frites", "🦪", "France / Belgium", "Use an empty shell as tongs. Then drink the broth.",
             u: [.hand, .spoon], m: 3, s: [0, 1], f: [3], h: [.protein], a: [2], w: [.mild, .cold], d: .omnivore),
        Meal("Bouillabaisse", "🐟", "Marseille, France", "A saffron seafood stew that takes itself very seriously.",
             u: [.spoon], m: 2, s: [0, 1], f: [3], h: [.protein], a: [2], w: [.cold, .mild], d: .omnivore),
        Meal("Beef Wellington", "🥩", "United Kingdom", "Pastry, mushroom duxelles, beef. The showpiece.",
             u: [.fork], m: 1, s: [0], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Paella Valenciana", "🥘", "Valencia, Spain", "Saffron rice with a crust at the bottom worth fighting over.",
             u: [.fork], m: 2, s: [0, 1], f: [3], h: [.carbs], a: [3], w: [.hot, .mild], d: .omnivore),
        Meal("Patatas Bravas", "🥔", "Spain", "Fried potatoes under a spicy sauce, eaten with a toothpick or not.",
             u: [.hand, .fork], m: 2, s: [1, 2], f: [1, 2], h: [.carbs], a: [1], w: [.hot, .mild], d: .vegan),
        Meal("Gazpacho", "🍅", "Andalusia, Spain", "Cold soup for hot days. Absolutely no cooking involved.",
             u: [.spoon], m: 1, s: [0, 1], f: [3], h: [.vegetable], a: [1], w: [.hot], d: .vegan),
        Meal("Tortilla Española", "🥚", "Spain", "Potato and egg, thick as a book, good at any temperature.",
             u: [.fork], m: 1, s: [0], f: [2, 3], h: [.carbs], a: [2], w: [.mild, .hot], d: .vegetarian),
        Meal("Moussaka", "🍆", "Greece", "Eggplant, lamb, béchamel. Structurally magnificent.",
             u: [.fork], m: 2, s: [0], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Chicken Souvlaki Pita", "🥙", "Greece", "Wrapped in foil, dripping tzatziki, eaten on the move.",
             u: [.hand], m: 2, s: [0, 1], f: [1, 2], h: [.protein], a: [2], w: [.hot], d: .omnivore),
        Meal("Greek Village Salad", "🥗", "Greece", "No lettuce. Just tomatoes, feta, and good olive oil.",
             u: [.fork], m: 1, s: [0], f: [2, 3], h: [.vegetable], a: [1], w: [.hot], d: .vegetarian),
        Meal("Spanakopita", "🥬", "Greece", "Spinach and feta between shattering layers of phyllo.",
             u: [.hand, .fork], m: 2, s: [0], f: [2, 3], h: [.vegetable, .carbs], a: [1, 2], w: [.mild, .cold], d: .vegetarian)
        ]
    }

    private static func part3() -> [Meal] {
        [
        Meal("Fish and Chips", "🍟", "United Kingdom", "Vinegar, newspaper, and rain outside. The full experience.",
             u: [.hand, .fork], m: 2, s: [0], f: [1, 2], h: [.protein, .carbs], a: [3], w: [.cold], d: .omnivore),
        Meal("Shepherd's Pie", "🥧", "United Kingdom / Ireland", "Lamb under a mashed potato roof. Dig in with a fork.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.protein, .carbs], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Bangers and Mash with Onion Gravy", "🌭", "United Kingdom", "Sausages, potato, gravy. A pub in food form.",
             u: [.fork], m: 2, s: [0], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Steak and Ale Pie", "🥧", "United Kingdom", "A proper crust with beef and dark beer underneath.",
             u: [.fork], m: 2, s: [0], f: [2, 3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Irish Beef Stew", "🍲", "Ireland", "Barley, beef, and a spoon. Rain optional but recommended.",
             u: [.spoon], m: 2, s: [0], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Wiener Schnitzel with Spätzle", "🍽️", "Austria / Germany", "Pounded thin, fried gold, squeezed with lemon.",
             u: [.fork], m: 2, s: [0], f: [2, 3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Swedish Meatballs", "🍛", "Sweden", "Cream gravy, lingonberry, and a quiet kind of joy.",
             u: [.fork], m: 2, s: [0], f: [2, 3], h: [.protein], a: [2, 3], w: [.cold], d: .omnivore),
        Meal("Pierogi with Caramelized Onions", "🥟", "Poland", "Potato dumplings pan-fried in butter until the edges crisp.",
             u: [.fork], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [2, 3], w: [.cold], d: .vegetarian),
        Meal("Hungarian Goulash", "🍲", "Hungary", "Paprika does the heavy lifting. So does the bread you dunk.",
             u: [.spoon], m: 2, s: [1], f: [2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Borscht", "🥣", "Ukraine", "Beet-red, faintly sweet, and better on the second day.",
             u: [.spoon], m: 1, s: [0], f: [2, 3], h: [.vegetable], a: [1], w: [.cold], d: .vegan),
        Meal("Cheese Fondue", "🫕", "Switzerland", "Spear the bread. Don't drop it. There are rules.",
             u: [.hand], m: 2, s: [0], f: [3], h: [.carbs], a: [2], w: [.cold], d: .vegetarian),
        Meal("Falafel Wrap with Tahini", "🥙", "Levant", "Crunchy chickpea fritters, pickles, and sauce down your arm.",
             u: [.hand], m: 2, s: [1], f: [1, 2], h: [.protein], a: [2], w: [.hot, .mild], d: .vegan),
        Meal("Chicken Shawarma Plate", "🍢", "Levant", "Shaved off the spit, piled on rice, garlic sauce everywhere.",
             u: [.fork], m: 2, s: [1], f: [2], h: [.protein], a: [3], w: [.mild, .hot], d: .omnivore),
        Meal("Mezze Spread with Hummus and Pita", "🫓", "Levant", "A table of small plates and everyone reaching across it.",
             u: [.hand], m: 2, s: [0, 1], f: [2, 3], h: [.vegetable], a: [1, 2], w: [.hot], d: .vegan),
        Meal("Lamb Shish Kebab", "🍢", "Turkey", "Charred off the skewer with grilled peppers and flatbread.",
             u: [.hand, .fork], m: 2, s: [0, 1], f: [2, 3], h: [.protein], a: [2, 3], w: [.hot, .mild], d: .omnivore),
        Meal("Lamb Tagine with Apricots", "🍲", "Morocco", "Sweet, savory, slow, and served under a conical hat.",
             u: [.fork, .spoon], m: 2, s: [1], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Vegetable Couscous Tagine", "🥕", "Morocco", "Seven vegetables over fluffy couscous, warm with ras el hanout.",
             u: [.fork, .spoon], m: 2, s: [1], f: [3], h: [.vegetable], a: [2], w: [.cold, .mild], d: .vegan),
        Meal("Shakshuka", "🍳", "North Africa / Levant", "Eggs poached in spiced tomato, bread doing the scooping.",
             u: [.spoon, .hand], m: 2, s: [1, 2], f: [1, 2], h: [.protein], a: [2], w: [.cold], d: .vegetarian),
        Meal("Mujadara", "🍚", "Levant", "Lentils, rice, and a mountain of fried onions. Humble and perfect.",
             u: [.fork, .spoon], m: 1, s: [0, 1], f: [1, 2], h: [.carbs], a: [2], w: [.cold, .mild], d: .vegan),
        Meal("Koshari", "🍛", "Egypt", "Rice, lentils, pasta, chickpeas, crispy onions, hot sauce. All of it.",
             u: [.fork, .spoon], m: 2, s: [1, 2], f: [1, 2], h: [.carbs], a: [3], w: [.cold, .mild], d: .vegan),
        Meal("Fesenjan (Pomegranate Walnut Stew)", "🥘", "Iran", "Dark, tangy, nutty, and unlike anything else on the table.",
             u: [.fork, .spoon], m: 2, s: [0, 1], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Jollof Rice with Grilled Chicken", "🍚", "Nigeria / Ghana", "Smoky tomato rice worth every argument about who makes it best.",
             u: [.fork, .spoon], m: 2, s: [1, 2], f: [2], h: [.carbs], a: [3], w: [.hot, .mild], d: .omnivore),
        Meal("Doro Wat with Injera", "🍗", "Ethiopia", "Berbere-red chicken stew you scoop with spongy flatbread. No cutlery.",
             u: [.hand], m: 3, s: [2], f: [2, 3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Ethiopian Vegetable Combo", "🫓", "Ethiopia", "Lentils, greens, and shiro on injera — tear, scoop, repeat.",
             u: [.hand], m: 3, s: [1, 2], f: [2, 3], h: [.vegetable], a: [2, 3], w: [.cold, .mild], d: .vegan),
        Meal("Suya Skewers", "🍢", "Nigeria", "Peanut-chile crusted beef off a charcoal grill. Napkins are theoretical.",
             u: [.hand], m: 2, s: [2], f: [1, 2], h: [.protein], a: [2], w: [.hot], d: .omnivore),
        Meal("West African Peanut Stew", "🥜", "West Africa", "Groundnut, tomato, sweet potato — thick enough to hold a spoon up.",
             u: [.spoon], m: 2, s: [1, 2], f: [1, 2], h: [.vegetable, .protein], a: [3], w: [.cold], d: .vegan),
        Meal("Thieboudienne", "🐟", "Senegal", "Fish and broken rice cooked in one pot, the national dish for good reason.",
             u: [.fork, .spoon], m: 2, s: [1], f: [2], h: [.carbs, .protein], a: [3], w: [.mild, .hot], d: .omnivore),
        Meal("Egusi Soup with Pounded Yam", "🥣", "Nigeria", "Melon-seed stew, eaten with your right hand. Gloriously messy.",
             u: [.hand], m: 3, s: [2], f: [2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Bobotie", "🍛", "South Africa", "Curried mince under a savory custard, with chutney on the side.",
             u: [.fork], m: 2, s: [1], f: [2, 3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Chakalaka with Pap", "🌽", "South Africa", "Spicy vegetable relish over maize porridge. Cheap, hot, brilliant.",
             u: [.spoon, .fork], m: 2, s: [2], f: [1], h: [.vegetable, .carbs], a: [2], w: [.mild, .cold], d: .vegan),
        Meal("Butter Chicken with Naan", "🍛", "India", "Tomato, cream, and bread you use as a spoon.",
             u: [.hand, .fork], m: 2, s: [1], f: [2, 3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Lamb Vindaloo", "🌶️", "Goa, India", "Vinegar and chiles in a fight. You are the venue.",
             u: [.fork, .spoon], m: 2, s: [2], f: [2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Chicken Biryani", "🍚", "India / Pakistan", "Layered, saffroned, and lifted from the pot like treasure.",
             u: [.fork, .spoon], m: 2, s: [1, 2], f: [2, 3], h: [.carbs], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Tandoori Chicken", "🍗", "Punjab, India", "Yogurt-marinated, blistered in a hot oven, eaten off the bone.",
             u: [.hand], m: 2, s: [1], f: [2, 3], h: [.protein], a: [2], w: [.hot, .mild], d: .omnivore),
        Meal("Chana Masala with Rice", "🍛", "India", "Chickpeas in a spiced tomato gravy. Weeknight hero.",
             u: [.fork, .spoon], m: 2, s: [1, 2], f: [1, 2], h: [.protein, .vegetable], a: [2], w: [.cold, .mild], d: .vegan),
        Meal("Palak Paneer", "🥬", "North India", "Creamed spinach with cheese cubes that squeak a little.",
             u: [.fork, .spoon], m: 2, s: [1], f: [2, 3], h: [.vegetable], a: [2], w: [.cold], d: .vegetarian),
        Meal("Masala Dosa", "🫓", "South India", "A crisp metre-long crepe around spiced potato. Hands only.",
             u: [.hand], m: 2, s: [1], f: [1, 2], h: [.carbs], a: [2], w: [.mild, .hot], d: .vegan),
        Meal("Dal Tadka with Rice", "🥣", "India", "Lentils, ghee-fried spices, done. The definition of light and warm.",
             u: [.spoon], m: 1, s: [1], f: [1, 2], h: [.protein], a: [1], w: [.cold], d: .vegetarian),
        Meal("Aloo Gobi", "🥔", "India", "Potato and cauliflower, turmeric-yellow, dry-fried and simple.",
             u: [.fork, .spoon], m: 1, s: [1], f: [1, 2], h: [.vegetable], a: [1, 2], w: [.mild, .cold], d: .vegan),
        Meal("Samosa Chaat", "🥟", "India", "Smashed samosas, chutneys, yogurt, chaos. Eat immediately.",
             u: [.hand, .spoon], m: 3, s: [1, 2], f: [1], h: [.carbs], a: [1, 2], w: [.mild, .hot], d: .vegetarian)
        ]
    }

    private static func part4() -> [Meal] {
        [
        Meal("Baingan Bharta", "🍆", "India", "Smoke-roasted eggplant mashed with tomato and green chile.",
             u: [.fork, .spoon], m: 2, s: [1, 2], f: [2], h: [.vegetable], a: [2], w: [.cold, .mild], d: .vegan),
        Meal("Tonkotsu Ramen", "🍜", "Japan", "Slurp loudly. The broth will end up on your chin regardless.",
             u: [.chopsticks, .spoon], m: 3, s: [0, 1], f: [1, 2], h: [.carbs], a: [3], w: [.cold], d: .omnivore),
        Meal("Nigiri Sushi Platter", "🍣", "Japan", "Cold, precise, and over before you've made a single crumb.",
             u: [.chopsticks], m: 1, s: [0, 1], f: [3], h: [.protein], a: [1, 2], w: [.hot, .mild], d: .omnivore),
        Meal("Chirashi Bowl", "🍱", "Japan", "Sashimi scattered over vinegared rice. Lunch's fancy cousin.",
             u: [.chopsticks], m: 1, s: [0, 1], f: [3], h: [.protein], a: [2], w: [.hot, .mild], d: .omnivore),
        Meal("Chicken Katsu Curry", "🍛", "Japan", "Crunchy cutlet, thick brown curry, rice. Undefeated.",
             u: [.chopsticks, .fork, .spoon], m: 2, s: [1], f: [1, 2], h: [.carbs], a: [3], w: [.cold], d: .omnivore),
        Meal("Grilled Salmon Teishoku", "🐟", "Japan", "Fish, rice, miso, pickles. Balanced to an almost annoying degree.",
             u: [.chopsticks], m: 1, s: [0], f: [3], h: [.protein], a: [1, 2], w: [.mild, .hot], d: .omnivore),
        Meal("Gyoza", "🥟", "Japan", "Crisp on one side, soft on the other, gone in four bites.",
             u: [.chopsticks], m: 1, s: [0, 1], f: [1, 2], h: [.protein], a: [1], w: [.mild, .cold], d: .omnivore),
        Meal("Kitsune Udon", "🍜", "Japan", "Fat noodles, clear broth, sweet fried tofu on top.",
             u: [.chopsticks, .spoon], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [1, 2], w: [.cold], d: .vegetarian),
        Meal("Vegetable Tempura", "🍤", "Japan", "Lacy, weightless, dipped in broth. Impossibly neat for fried food.",
             u: [.chopsticks], m: 1, s: [0], f: [3], h: [.vegetable], a: [1], w: [.mild, .hot], d: .vegan),
        Meal("Bibimbap", "🍲", "Korea", "Stir it all together in the hot stone bowl. That's the fun part.",
             u: [.spoon, .chopsticks], m: 2, s: [1, 2], f: [2, 3], h: [.vegetable], a: [2], w: [.cold, .mild], d: .vegetarian),
        Meal("Korean BBQ Bulgogi Ssam", "🥬", "Korea", "Grill it, wrap it in lettuce, eat it in one go. Sauce will escape.",
             u: [.hand, .chopsticks], m: 3, s: [1, 2], f: [2, 3], h: [.protein], a: [3], w: [.mild, .cold], d: .omnivore),
        Meal("Tteokbokki", "🌶️", "Korea", "Chewy rice cakes in a red sauce that does not negotiate.",
             u: [.chopsticks], m: 2, s: [2], f: [1], h: [.carbs], a: [1, 2], w: [.cold], d: .vegetarian),
        Meal("Kimchi Jjigae", "🍲", "Korea", "Sour, spicy, bubbling. The cure for a bad day and cold weather.",
             u: [.spoon], m: 2, s: [2], f: [1, 2], h: [.protein], a: [2], w: [.cold], d: .omnivore),
        Meal("Japchae", "🍝", "Korea", "Glass noodles, sesame, vegetables. Light but never boring.",
             u: [.chopsticks], m: 1, s: [0, 1], f: [2, 3], h: [.carbs, .vegetable], a: [1, 2], w: [.mild, .hot], d: .vegan),
        Meal("Xiao Long Bao (Soup Dumplings)", "🥟", "Shanghai, China", "Bite too early and the soup goes down your shirt. Every time.",
             u: [.chopsticks], m: 3, s: [0, 1], f: [2, 3], h: [.protein], a: [1, 2], w: [.cold], d: .omnivore),
        Meal("Mapo Tofu", "🌶️", "Sichuan, China", "Numbing peppercorn, chile bean paste, silky tofu. Serious heat.",
             u: [.chopsticks, .spoon], m: 2, s: [2], f: [1, 2], h: [.protein], a: [2], w: [.cold], d: .omnivore),
        Meal("Vegan Mapo Tofu", "🌶️", "Sichuan, China", "Mushrooms instead of pork, and the peppercorns don't care.",
             u: [.chopsticks, .spoon], m: 2, s: [2], f: [1, 2], h: [.protein], a: [2], w: [.cold], d: .vegan),
        Meal("Kung Pao Chicken", "🥜", "Sichuan, China", "Peanuts, dried chiles, and a wok that was extremely hot.",
             u: [.chopsticks], m: 2, s: [1, 2], f: [1, 2], h: [.protein], a: [2], w: [.cold, .mild], d: .omnivore),
        Meal("Dan Dan Noodles", "🍜", "Sichuan, China", "Toss from the bottom. Sesame, chile oil, and a red-stained bowl.",
             u: [.chopsticks], m: 2, s: [2], f: [1, 2], h: [.carbs], a: [2], w: [.cold], d: .omnivore),
        Meal("Peking Duck Pancakes", "🦆", "Beijing, China", "Lacquered skin, thin pancakes, and a little ceremony at the table.",
             u: [.hand], m: 2, s: [0], f: [3], h: [.protein], a: [2], w: [.cold, .mild], d: .omnivore),
        Meal("Char Siu Rice Plate", "🍚", "Cantonese, China", "Glossy barbecue pork over rice, with greens to feel virtuous.",
             u: [.chopsticks, .fork], m: 2, s: [0], f: [1, 2], h: [.protein], a: [3], w: [.mild, .cold], d: .omnivore),
        Meal("Congee with Scallions", "🥣", "China", "Rice porridge. Gentle, warm, and asks nothing of you.",
             u: [.spoon], m: 1, s: [0], f: [1, 2], h: [.carbs], a: [1], w: [.cold], d: .vegan),
        Meal("Stir-Fried Garlic Bok Choy with Tofu", "🥬", "China", "Fifteen minutes, one wok, no regrets.",
             u: [.chopsticks], m: 1, s: [0, 1], f: [1, 2], h: [.vegetable, .protein], a: [1], w: [.hot, .mild], d: .vegan),
        Meal("Pad Thai", "🍤", "Thailand", "Tamarind, peanuts, lime. The gateway noodle.",
             u: [.chopsticks, .fork], m: 2, s: [1], f: [1, 2], h: [.carbs], a: [2], w: [.hot, .mild], d: .omnivore),
        Meal("Green Curry with Jasmine Rice", "🍛", "Thailand", "Coconut milk softens the blow. Slightly.",
             u: [.spoon, .fork], m: 2, s: [2], f: [2, 3], h: [.vegetable, .protein], a: [2], w: [.cold, .mild], d: .vegan),
        Meal("Tom Yum Goong", "🍤", "Thailand", "Sour, hot, fragrant. Clears your sinuses and your mood.",
             u: [.spoon], m: 1, s: [2], f: [2, 3], h: [.protein], a: [1], w: [.cold, .mild], d: .omnivore),
        Meal("Massaman Curry", "🥘", "Thailand", "Potatoes, peanuts, warm spices. The gentle curry.",
             u: [.spoon, .fork], m: 2, s: [1], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Tofu Larb", "🌿", "Laos / Thailand", "Herby, limey, fiery, wrapped in lettuce leaves.",
             u: [.hand, .spoon], m: 2, s: [2], f: [2], h: [.protein, .vegetable], a: [1], w: [.hot], d: .vegan),
        Meal("Phở Bò", "🍜", "Vietnam", "Broth simmered overnight, noodles, herbs you add yourself.",
             u: [.chopsticks, .spoon], m: 3, s: [0, 1], f: [1, 2], h: [.carbs], a: [2, 3], w: [.cold], d: .omnivore),
        Meal("Vegetable Phở", "🍜", "Vietnam", "Star anise and charred ginger doing all the heavy lifting.",
             u: [.chopsticks, .spoon], m: 3, s: [0, 1], f: [1, 2], h: [.carbs], a: [2], w: [.cold], d: .vegan),
        Meal("Bánh Mì", "🥖", "Vietnam", "A crackly baguette, pickles, cilantro, chile. Crumbs everywhere.",
             u: [.hand], m: 2, s: [1], f: [1, 2], h: [.protein, .carbs], a: [2], w: [.hot, .mild], d: .omnivore),
        Meal("Vietnamese Summer Rolls", "🌯", "Vietnam", "Cold, translucent, dipped in peanut sauce. Neat as it gets.",
             u: [.hand], m: 1, s: [0, 1], f: [2, 3], h: [.vegetable], a: [1], w: [.hot], d: .vegan),
        Meal("Nasi Goreng", "🍳", "Indonesia", "Fried rice with a fried egg on top, because of course.",
             u: [.fork, .spoon], m: 2, s: [1, 2], f: [1, 2], h: [.carbs], a: [2], w: [.hot, .mild], d: .omnivore),
        Meal("Chicken Adobo", "🍗", "Philippines", "Vinegar, soy, garlic, bay. Three ingredients, endless depth.",
             u: [.spoon, .fork], m: 2, s: [0, 1], f: [1, 2], h: [.protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Hainanese Chicken Rice", "🍚", "Singapore / Hainan", "Poached chicken, fragrant rice, three sauces. Deceptively simple.",
             u: [.chopsticks, .spoon], m: 1, s: [0, 1], f: [2, 3], h: [.protein], a: [2], w: [.hot, .mild], d: .omnivore),
        Meal("Laksa", "🍜", "Malaysia / Singapore", "Coconut curry noodle soup that splashes and doesn't apologize.",
             u: [.chopsticks, .spoon], m: 3, s: [2], f: [1, 2], h: [.carbs], a: [3], w: [.cold], d: .omnivore),
        Meal("Mushroom Wellington", "🍄", "British-inspired, vegan", "Puff pastry and mushroom duxelles. The centerpiece, minus the beef.",
             u: [.fork], m: 1, s: [0], f: [3], h: [.protein, .vegetable], a: [3], w: [.cold], d: .vegan),
        Meal("Roasted Cauliflower Steak", "🥦", "Modern vegetarian", "Charred edges, tahini drizzle, and a knife you barely need.",
             u: [.fork], m: 1, s: [0, 1], f: [3], h: [.vegetable], a: [1], w: [.mild, .cold], d: .vegan),
        Meal("Black Bean Burger", "🍔", "American vegan", "Holds together, tastes great, and yes it's actually a burger.",
             u: [.hand], m: 2, s: [1], f: [1, 2], h: [.protein], a: [2], w: [.mild, .hot], d: .vegan, k: true),
        Meal("Vegan Chili", "🌶️", "American vegan", "Three beans, chipotle, and a pot that feeds you twice.",
             u: [.spoon], m: 2, s: [1, 2], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .vegan, k: true)
        ]
    }

    private static func part5() -> [Meal] {
        [
        Meal("Lentil Shepherd's Pie", "🥧", "British vegan", "Same mashed potato roof, entirely different foundation.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.protein, .carbs], a: [3], w: [.cold], d: .vegan, k: true),
        Meal("Butternut Squash Soup", "🎃", "Modern vegan", "Velvety, sweet, and blitzed smooth. Bowl, blanket, done.",
             u: [.spoon], m: 1, s: [0, 1], f: [2, 3], h: [.vegetable], a: [1], w: [.cold], d: .vegan, k: true),
        Meal("Buddha Bowl with Tahini", "🥗", "Modern vegan", "Grains, roasted vegetables, chickpeas, sauce. Assembled, not cooked.",
             u: [.fork], m: 1, s: [0, 1], f: [2], h: [.vegetable], a: [2], w: [.hot, .mild], d: .vegan),
        Meal("Vegan Poke Bowl", "🥑", "Hawaii, vegan", "Marinated watermelon or tofu over cold rice. Summer in a bowl.",
             u: [.chopsticks, .fork], m: 1, s: [0, 1], f: [2, 3], h: [.vegetable], a: [1, 2], w: [.hot], d: .vegan),
        Meal("Vegan Ramen", "🍜", "Japan, vegan", "Miso-mushroom broth with corn and chile oil. Slurp away.",
             u: [.chopsticks, .spoon], m: 3, s: [1, 2], f: [1, 2], h: [.carbs], a: [3], w: [.cold], d: .vegan),
        Meal("Stuffed Bell Peppers", "🫑", "Mediterranean vegetarian", "Rice, herbs, and whatever else needed using up.",
             u: [.fork], m: 2, s: [0, 1], f: [2], h: [.vegetable], a: [2], w: [.cold, .mild], d: .vegan, k: true),
        Meal("Watermelon and Feta Salad", "🍉", "Mediterranean", "Cold, salty, sweet. The only sensible answer in a heatwave.",
             u: [.fork], m: 1, s: [0], f: [3], h: [.vegetable], a: [1], w: [.hot], d: .vegetarian),
        Meal("Veggie Sushi Rolls", "🍙", "Japan, vegan", "Avocado, cucumber, pickled radish. Tidy little cylinders.",
             u: [.chopsticks], m: 1, s: [0, 1], f: [2, 3], h: [.vegetable], a: [1], w: [.hot, .mild], d: .vegan),
        Meal("Sheet-Pan Gnocchi and Tomatoes", "🍅", "Modern Italian", "One tray, blistered tomatoes, crisp gnocchi. Minimal washing up.",
             u: [.fork], m: 2, s: [0, 1], f: [1, 2], h: [.carbs], a: [2, 3], w: [.cold, .mild], d: .vegan, k: true),
        Meal("Vegan Bánh Mì", "🥖", "Vietnam, vegan", "Lemongrass tofu, pickled carrot, and a baguette that shatters.",
             u: [.hand], m: 2, s: [1, 2], f: [1, 2], h: [.protein, .carbs], a: [2], w: [.hot, .mild], d: .vegan),
        Meal("Vegan Jackfruit Tacos", "🌮", "Mexican-inspired vegan", "Pulled, saucy, and dripping the way pulled anything should.",
             u: [.hand], m: 3, s: [1, 2], f: [1, 2], h: [.vegetable], a: [2], w: [.hot, .mild], d: .vegan),
        Meal("Chilled Cucumber Avocado Soup", "🥒", "Modern vegan", "No stove involved. Just a blender and a hot afternoon.",
             u: [.spoon], m: 1, s: [0], f: [3], h: [.vegetable], a: [1], w: [.hot], d: .vegan),
        Meal("Vegan Pad See Ew", "🍜", "Thailand, vegan", "Wide noodles, charred greens, dark soy. Wok smoke included.",
             u: [.chopsticks, .fork], m: 2, s: [0, 1], f: [1, 2], h: [.carbs], a: [2, 3], w: [.mild, .cold], d: .vegan),
        Meal("Vegan Ethiopian Shiro Wat", "🥣", "Ethiopia, vegan", "Chickpea flour stew, spiced deep red, scooped with injera.",
             u: [.hand, .spoon], m: 3, s: [2], f: [1, 2], h: [.protein], a: [2], w: [.cold], d: .vegan),
        Meal("Truffle Tagliatelle", "🍝", "Piedmont, Italy", "Butter, cheese, and shaved truffle. Pinkies up, obviously.",
             u: [.fork], m: 2, s: [0], f: [3], h: [.carbs], a: [2], w: [.cold, .mild], d: .vegetarian),
        Meal("Vegan Mushroom Risotto", "🍄", "Italy, vegan", "Olive oil instead of butter, and nobody at the table notices.",
             u: [.fork, .spoon], m: 1, s: [0], f: [3], h: [.carbs], a: [2], w: [.cold], d: .vegan),
        Meal("Falafel Mezze Platter", "🧆", "Levant, vegan", "Hummus, baba ganoush, pickles, warm pita. Grazing at its finest.",
             u: [.hand], m: 2, s: [1], f: [3], h: [.protein], a: [2, 3], w: [.hot, .mild], d: .vegan),
        Meal("Vegan Sushi Temaki Cones", "🍥", "Japan, vegan", "Hand rolls you assemble yourself and eat immediately.",
             u: [.hand], m: 2, s: [0, 1], f: [2, 3], h: [.vegetable], a: [1, 2], w: [.hot], d: .vegan),
        Meal("Marry Me Chicken", "🍗", "American, viral", "Sun-dried tomato cream sauce, one pan, thirty minutes.",
             u: [.fork], m: 2, s: [0, 1], f: [2], h: [.protein], a: [2, 3], w: [.cold, .mild], d: .omnivore, k: true),
        Meal("Beef Stroganoff", "🍄", "Russian-American", "Sour cream, mushrooms, and egg noodles underneath it all.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.protein, .carbs], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Baked Ziti", "🧀", "Italian-American", "Ricotta, mozzarella, and the crispy bits at the edge of the dish.",
             u: [.fork], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [3], w: [.cold], d: .vegetarian, k: true),
        Meal("Broccoli Cheddar Soup", "🥦", "United States", "Thick, orange, and best in a hollowed-out bread bowl.",
             u: [.spoon], m: 1, s: [0], f: [1, 2], h: [.vegetable], a: [1, 2], w: [.cold], d: .vegetarian, k: true),
        Meal("Zuppa Toscana", "🥣", "Italian-American", "Sausage, kale, potatoes, cream. The restaurant copycat everyone makes.",
             u: [.spoon], m: 2, s: [1], f: [1, 2], h: [.protein], a: [2, 3], w: [.cold], d: .omnivore, k: true),
        Meal("Chicken and Dumplings", "🍲", "American South", "Soft dumplings dropped into broth. Pure cold-weather insulation.",
             u: [.spoon, .fork], m: 2, s: [0], f: [1, 2], h: [.protein, .carbs], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Shrimp Scampi", "🍤", "Italian-American", "Garlic, butter, white wine, lemon. Twenty minutes, start to finish.",
             u: [.fork], m: 2, s: [0, 1], f: [2, 3], h: [.protein, .carbs], a: [2], w: [.mild, .hot], d: .omnivore),
        Meal("Beef and Broccoli", "🥦", "Chinese-American", "Better than takeout, and you already have the soy sauce.",
             u: [.chopsticks, .fork], m: 2, s: [0, 1], f: [1, 2], h: [.protein], a: [2, 3], w: [.cold, .mild], d: .omnivore),
        Meal("General Tso's Chicken", "🍗", "Chinese-American", "Sweet, sticky, faintly fiery, and unapologetically not authentic.",
             u: [.chopsticks, .fork], m: 2, s: [1, 2], f: [1, 2], h: [.protein], a: [2, 3], w: [.cold, .mild], d: .omnivore),
        Meal("Fettuccine Alfredo", "🍝", "Italian-American", "Butter, cream, parmesan. No further questions.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.carbs], a: [3], w: [.cold], d: .vegetarian, k: true),
        Meal("Salisbury Steak", "🍖", "United States", "Beef patties drowned in onion gravy. Diner food, done at home.",
             u: [.fork], m: 2, s: [0], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Tuna Noodle Casserole", "🐟", "United States", "Pantry ingredients, crushed chips on top, zero pretense.",
             u: [.fork], m: 2, s: [0], f: [1], h: [.carbs], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Slow Cooker Chicken Taco Soup", "🌶️", "Tex-Mex", "Dump everything in at breakfast, eat it at dinner.",
             u: [.spoon], m: 2, s: [1, 2], f: [1], h: [.protein], a: [2, 3], w: [.cold], d: .omnivore, k: true),
        Meal("Egg Roll in a Bowl", "🥬", "American, low-carb", "All the filling, none of the wrapper. Done in fifteen minutes.",
             u: [.fork, .chopsticks], m: 1, s: [0, 1], f: [1, 2], h: [.protein, .vegetable], a: [1, 2], w: [.cold, .mild], d: .omnivore),
        Meal("Chicken Fried Steak", "🍳", "Texas, USA", "Battered, fried, and buried under peppery white gravy.",
             u: [.fork], m: 2, s: [0, 1], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("American Goulash", "🍝", "United States", "Elbow macaroni, ground beef, tomato. Feeds a crowd for nothing.",
             u: [.spoon, .fork], m: 2, s: [0, 1], f: [1], h: [.carbs], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Sheet-Pan Chicken Fajitas", "🫓", "Tex-Mex", "Peppers, onions, one tray, and tortillas you fill yourself.",
             u: [.hand], m: 2, s: [1], f: [1, 2], h: [.protein], a: [2, 3], w: [.hot, .mild], d: .omnivore),
        Meal("Buttermilk-Brined Roast Chicken", "🍗", "NYT Cooking", "Brined overnight, roasted hot. The one everybody saves.",
             u: [.fork, .hand], m: 2, s: [0], f: [2, 3], h: [.protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Momofuku Bo Ssam", "🥬", "Korean-American", "Slow-roasted pork shoulder, lettuce leaves, and a very messy table.",
             u: [.hand], m: 3, s: [1, 2], f: [2, 3], h: [.protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Lemony Shrimp and Bean Stew", "🍤", "NYT Cooking", "Pantry beans, quick shrimp, a lot of lemon. Thirty minutes.",
             u: [.spoon], m: 1, s: [0, 1], f: [2], h: [.protein], a: [1, 2], w: [.cold, .mild], d: .omnivore),
        Meal("Vietnamese Garlic Noodles", "🍜", "San Francisco / Vietnam", "An indecent amount of garlic and butter. That's the recipe.",
             u: [.chopsticks, .fork], m: 2, s: [0, 1], f: [1, 2], h: [.carbs], a: [2, 3], w: [.cold, .mild], d: .omnivore),
        Meal("Mississippi Roast", "🍖", "American South", "Chuck roast, pepperoncini, butter. Five ingredients, no effort.",
             u: [.fork], m: 2, s: [0, 1], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true)
        ]
    }

    private static func part6() -> [Meal] {
        [
        Meal("Peruvian Roast Chicken with Green Sauce", "🍗", "Peru", "Charred, cumin-rubbed, and served with a fiercely green sauce.",
             u: [.hand, .fork], m: 2, s: [1, 2], f: [2], h: [.protein], a: [3], w: [.mild, .hot], d: .omnivore),
        Meal("Spiced Chickpea Stew with Coconut and Turmeric", "🥣", "NYT Cooking", "Golden, creamy, and famous enough to have its own hashtag.",
             u: [.spoon], m: 2, s: [1], f: [2], h: [.protein, .vegetable], a: [2], w: [.cold], d: .vegan),
        Meal("Caramelized Shallot Pasta", "🧅", "NYT Cooking", "Shallots cooked far longer than feels reasonable. Worth it.",
             u: [.fork], m: 2, s: [1], f: [2, 3], h: [.carbs], a: [2], w: [.cold, .mild], d: .omnivore),
        Meal("Pasta alla Vodka", "🍝", "Italian-American", "Tomato, cream, a splash of vodka, and shockingly good results.",
             u: [.fork], m: 2, s: [0, 1], f: [2], h: [.carbs], a: [2, 3], w: [.cold], d: .vegetarian),
        Meal("Chicken Marbella", "🫒", "Silver Palate / NYT", "Prunes, olives and capers. Dinner-party food since 1979.",
             u: [.fork], m: 2, s: [0], f: [3], h: [.protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Red Lentil Soup with Lemon", "🍋", "NYT Cooking", "Cumin, lemon, and thirty minutes between you and dinner.",
             u: [.spoon], m: 1, s: [1], f: [2], h: [.protein], a: [1], w: [.cold], d: .vegan),
        Meal("Cold Sesame Noodles", "🥜", "NYT Cooking", "Sesame paste, chile oil, scallions. Better straight from the fridge.",
             u: [.chopsticks, .fork], m: 2, s: [0, 1], f: [1, 2], h: [.carbs], a: [2], w: [.hot], d: .vegan),
        Meal("Gochujang Buttered Noodles", "🌶️", "NYT Cooking", "Five ingredients, ten minutes, and a genuinely serious kick.",
             u: [.chopsticks, .fork], m: 2, s: [2], f: [1, 2], h: [.carbs], a: [2], w: [.cold], d: .vegetarian),
        Meal("Miso-Butter Salmon", "🐟", "NYT Cooking", "Sweet, salty, caramelized under the broiler in ten minutes.",
             u: [.fork, .chopsticks], m: 1, s: [0], f: [3], h: [.protein], a: [2], w: [.cold, .mild], d: .omnivore),
        Meal("Chicken Piccata", "🍋", "Italian-American", "Lemon, capers, butter. Elegant on a weeknight budget.",
             u: [.fork], m: 1, s: [0], f: [3], h: [.protein], a: [2], w: [.mild, .cold], d: .omnivore),
        Meal("Red Wine Braised Short Ribs", "🍖", "NYT Cooking", "Three hours in the oven and the fork does the carving.",
             u: [.fork], m: 2, s: [0], f: [3], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Baked Feta Pasta", "🧀", "Viral / NYT Cooking", "A block of feta, a tray of tomatoes, and one stir at the end.",
             u: [.fork], m: 2, s: [0, 1], f: [2], h: [.carbs], a: [2, 3], w: [.cold, .mild], d: .vegetarian),
        Meal("Mushroom Bourguignon", "🍄", "Smitten Kitchen", "All the red-wine depth of the beef version, none of the beef.",
             u: [.fork, .spoon], m: 2, s: [0], f: [2, 3], h: [.vegetable, .protein], a: [3], w: [.cold], d: .vegan),
        Meal("Chicken Paprikash", "🥘", "Hungary", "Sweet paprika, sour cream, and buttered noodles to catch it.",
             u: [.fork, .spoon], m: 2, s: [1], f: [2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Kimchi Fried Rice", "🍚", "Korea", "Old rice, older kimchi, a fried egg on top. Peak refrigerator cooking.",
             u: [.spoon, .chopsticks], m: 2, s: [1, 2], f: [1, 2], h: [.carbs], a: [2], w: [.cold, .mild], d: .omnivore),
        Meal("Chicken Tikka Masala", "🍛", "British-Indian", "Charred chicken in a spiced tomato cream. The nation's favourite.",
             u: [.fork, .spoon], m: 2, s: [1, 2], f: [2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Pizza Beans", "🫘", "Smitten Kitchen", "Beans, greens and molten mozzarella. The internet's favourite bean pot.",
             u: [.spoon, .fork], m: 2, s: [0, 1], f: [1, 2], h: [.protein, .vegetable], a: [2, 3], w: [.cold], d: .vegetarian),
        Meal("Zucchini Butter Spaghetti", "🥒", "Smitten Kitchen", "Zucchini cooked down to a jammy butter. Three ingredients, no sauce.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.carbs], a: [2], w: [.hot, .mild], d: .vegetarian),
        Meal("Baked Orzo with Eggplant and Mozzarella", "🍆", "Smitten Kitchen", "Pasta that behaves like a casserole, with a browned cheese lid.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.carbs], a: [3], w: [.cold], d: .vegetarian),
        Meal("Chicken with Forty Cloves of Garlic", "🧄", "Smitten Kitchen", "Forty. The cloves go sweet and spreadable, and nobody complains.",
             u: [.fork], m: 2, s: [0], f: [3], h: [.protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Spinach and Cheese Strata", "🥬", "Smitten Kitchen", "Custardy bread pudding gone savoury. Assembles the night before.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.carbs], a: [2, 3], w: [.cold], d: .vegetarian),
        Meal("Tomato and Corn Pie", "🌽", "Smitten Kitchen", "August in a pie tin, under a biscuit crust.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.vegetable], a: [2], w: [.hot], d: .vegetarian),
        Meal("Charred Cauliflower Quesadillas", "🫓", "Smitten Kitchen", "Blistered cauliflower and cheese, folded and griddled.",
             u: [.hand], m: 2, s: [1], f: [1, 2], h: [.vegetable], a: [2], w: [.mild, .hot], d: .vegetarian),
        Meal("Broccoli Parmesan Fritters", "🥦", "Smitten Kitchen", "Crisp-edged, cheesy, and gone before they reach the table.",
             u: [.hand, .fork], m: 2, s: [0], f: [1, 2], h: [.vegetable], a: [1, 2], w: [.mild, .cold], d: .vegetarian),
        Meal("Butternut Squash and Caramelized Onion Galette", "🎃", "Smitten Kitchen", "A free-form tart with a rye crust. Deliberately uneven, entirely the point.",
             u: [.fork, .hand], m: 2, s: [0], f: [3], h: [.vegetable], a: [2], w: [.cold], d: .vegetarian),
        Meal("Sheet Pan Chicken Tikka", "🍗", "Smitten Kitchen", "Yogurt-marinated chicken over cauliflower and potatoes. One tray.",
             u: [.fork], m: 2, s: [1, 2], f: [2], h: [.protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Smoky Sheet Pan Chicken with Cauliflower", "🔥", "Smitten Kitchen", "Smoked paprika, one pan, and almost nothing to wash up.",
             u: [.fork], m: 2, s: [1], f: [2], h: [.protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Spaghetti Carbonara Pie", "🍝", "Smitten Kitchen", "Carbonara baked until it slices. Yes, slices.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.carbs], a: [3], w: [.cold], d: .omnivore),
        Meal("Burst Tomato Galette with Corn and Zucchini", "🍅", "Smitten Kitchen", "Summer vegetables collapsed into a craggy free-form tart.",
             u: [.fork], m: 2, s: [0], f: [3], h: [.vegetable], a: [2], w: [.hot], d: .vegetarian),
        Meal("Broccoli Melts", "🥪", "Smitten Kitchen", "Garlicky broccoli mashed onto toast under cheese. Dinner in fifteen.",
             u: [.hand], m: 2, s: [0, 1], f: [1, 2], h: [.vegetable], a: [1, 2], w: [.mild, .cold], d: .vegetarian),
        Meal("Miso Maple Ribs", "🍖", "Smitten Kitchen", "Sticky, salty-sweet, and eaten entirely with your hands.",
             u: [.hand], m: 3, s: [0, 1], f: [2, 3], h: [.protein], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Everyday Meatballs", "🍝", "Smitten Kitchen", "Simmered straight in the sauce, no browning step, no fuss.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Lentil Soup with Sausage", "🥣", "Smitten Kitchen", "Smoky sausage, soft lentils, and a pot that improves overnight.",
             u: [.spoon], m: 1, s: [0, 1], f: [1, 2], h: [.protein], a: [2, 3], w: [.cold], d: .omnivore),
        Meal("Chicken Milanese", "🍗", "Smitten Kitchen", "Pounded thin, fried crisp, buried under a lemony pile of greens.",
             u: [.fork], m: 1, s: [0], f: [3], h: [.protein], a: [2, 3], w: [.mild, .hot], d: .omnivore),
        Meal("Corn Chowder", "🌽", "Smitten Kitchen", "Sweet corn, potatoes, and a broth made from the stripped cobs.",
             u: [.spoon], m: 1, s: [0], f: [2], h: [.vegetable], a: [1, 2], w: [.mild, .cold], d: .vegetarian),
        Meal("Leek Fritters", "🧅", "Smitten Kitchen", "Soft inside, lacy outside, with a garlicky yogurt to dunk them in.",
             u: [.hand, .fork], m: 2, s: [0], f: [2], h: [.vegetable], a: [1], w: [.mild, .cold], d: .vegetarian),
        Meal("Winter Squash Pasta Bake", "🎃", "Smitten Kitchen", "Squash puréed into the sauce so nobody notices the vegetables.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.carbs], a: [3], w: [.cold], d: .vegetarian),
        Meal("Grilled Hot Dogs", "🌭", "United States", "Bun, mustard, done. Nobody has ever needed a recipe.",
             u: [.hand], m: 2, s: [0], f: [1], h: [.protein, .carbs], a: [2], w: [.hot, .mild], d: .omnivore, k: true),
        Meal("BLT Sandwich", "🥓", "United States", "Bacon, lettuce, tomato, too much mayonnaise. Peak August.",
             u: [.hand], m: 2, s: [0], f: [1, 2], h: [.protein], a: [2], w: [.hot, .mild], d: .omnivore, k: true),
        Meal("Reuben Sandwich", "🥪", "United States", "Corned beef, kraut, Russian dressing, griddled until it leaks.",
             u: [.hand], m: 3, s: [0], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .omnivore)
        ]
    }

    private static func part7() -> [Meal] {
        [
        Meal("French Dip Sandwich", "🥖", "California, USA", "Roast beef on a roll with a cup of jus for dunking.",
             u: [.hand], m: 3, s: [0], f: [2], h: [.protein], a: [3], w: [.cold], d: .omnivore),
        Meal("Meatball Sub", "🍝", "Italian-American", "Sauce down your wrist within two bites. Accept it.",
             u: [.hand], m: 3, s: [0], f: [1], h: [.protein, .carbs], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Italian Sub", "🥖", "Italian-American", "Cold cuts, provolone, oil and vinegar, shredded lettuce.",
             u: [.hand], m: 2, s: [0, 1], f: [1], h: [.protein], a: [2, 3], w: [.hot, .mild], d: .omnivore),
        Meal("Tuna Melt", "🧀", "United States", "Diner food at its most unpretentious, and better for it.",
             u: [.hand], m: 2, s: [0], f: [1], h: [.protein], a: [2], w: [.cold, .mild], d: .omnivore, k: true),
        Meal("Chicken Salad Sandwich", "🥪", "United States", "Celery, mayo, soft bread. Lunch that wandered into dinner.",
             u: [.hand], m: 1, s: [0], f: [1, 2], h: [.protein], a: [1, 2], w: [.hot, .mild], d: .omnivore, k: true),
        Meal("Patty Melt", "🍔", "United States", "A burger and a grilled cheese, on rye, with griddled onions.",
             u: [.hand], m: 3, s: [0], f: [1], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Turkey Burger", "🍔", "United States", "The lighter burger, which is still very much a burger.",
             u: [.hand], m: 2, s: [0, 1], f: [1, 2], h: [.protein], a: [2], w: [.mild, .hot], d: .omnivore, k: true),
        Meal("Shrimp Po' Boy", "🍤", "Louisiana, USA", "Fried shrimp, remoulade, dressed. Lean forward over the plate.",
             u: [.hand], m: 3, s: [1], f: [1, 2], h: [.protein], a: [3], w: [.hot, .mild], d: .omnivore),
        Meal("Hard-Shell Beef Tacos", "🌮", "Tex-Mex", "The shell shatters on the first bite. It always does.",
             u: [.hand], m: 3, s: [1], f: [1], h: [.protein], a: [2], w: [.mild, .hot], d: .omnivore, k: true),
        Meal("Chicken Burrito Bowl", "🥗", "Tex-Mex", "Rice, beans, salsa, everything in one bowl and no wrapping.",
             u: [.fork], m: 1, s: [1, 2], f: [1, 2], h: [.protein], a: [2], w: [.hot, .mild], d: .omnivore),
        Meal("Chicken Quesadilla", "🫓", "Tex-Mex", "Griddled, cut in wedges, dipped in sour cream.",
             u: [.hand], m: 2, s: [0, 1], f: [1], h: [.protein], a: [2], w: [.mild, .hot], d: .omnivore, k: true),
        Meal("Bean and Cheese Burrito", "🌯", "Tex-Mex", "Cheap, filling, and better wrapped in foil.",
             u: [.hand], m: 2, s: [0, 1], f: [1], h: [.carbs], a: [2], w: [.mild, .hot], d: .vegetarian, k: true),
        Meal("Cheese Enchiladas", "🧀", "Tex-Mex", "Red chile gravy poured over the top and baked until bubbling.",
             u: [.fork], m: 2, s: [1], f: [1, 2], h: [.carbs], a: [2, 3], w: [.cold, .mild], d: .vegetarian, k: true),
        Meal("Beef Enchilada Casserole", "🍲", "Tex-Mex", "Layered rather than rolled, because nobody has that kind of time.",
             u: [.fork], m: 2, s: [1], f: [1, 2], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Orange Chicken", "🍊", "Chinese-American", "Sweet, sticky, crisp. The takeout order you always end up making.",
             u: [.fork, .chopsticks], m: 2, s: [0, 1], f: [1, 2], h: [.protein], a: [2, 3], w: [.cold, .mild], d: .omnivore),
        Meal("Beef Lo Mein", "🍜", "Chinese-American", "Soft noodles, soy, and vegetables you can pick around.",
             u: [.chopsticks, .fork], m: 2, s: [0, 1], f: [1, 2], h: [.carbs], a: [2, 3], w: [.cold, .mild], d: .omnivore, k: true),
        Meal("Chicken Fried Rice", "🍚", "Chinese-American", "Day-old rice, a hot pan, and whatever is in the fridge.",
             u: [.fork, .chopsticks], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [2], w: [.mild, .cold], d: .omnivore, k: true),
        Meal("Sweet and Sour Pork", "🍍", "Chinese-American", "Bright red sauce, pineapple, and no apologies for either.",
             u: [.chopsticks, .fork], m: 2, s: [0], f: [1, 2], h: [.protein], a: [2, 3], w: [.mild, .cold], d: .omnivore),
        Meal("Teriyaki Chicken Bowl", "🍱", "Japanese-American", "Glazed chicken over rice with broccoli. Weeknight autopilot.",
             u: [.chopsticks, .fork], m: 1, s: [0], f: [1, 2], h: [.protein], a: [2], w: [.mild, .hot], d: .omnivore),
        Meal("Pepperoni Pizza", "🍕", "United States", "The default order. Grease pooling in the cups is the good part.",
             u: [.hand], m: 2, s: [0, 1], f: [1, 2], h: [.carbs], a: [2, 3], w: [.mild, .cold], d: .omnivore, k: true),
        Meal("Chicken Tenders and Fries", "🍟", "United States", "Order it at thirty-five. Nobody is keeping score.",
             u: [.hand], m: 2, s: [0], f: [1], h: [.protein], a: [2, 3], w: [.mild, .hot], d: .omnivore, k: true),
        Meal("Chicken Cordon Bleu", "🍗", "American / Swiss", "Ham and cheese rolled inside chicken, breaded, and baked.",
             u: [.fork], m: 2, s: [0], f: [2, 3], h: [.protein], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Pork Chops with Applesauce", "🍎", "United States", "Pan-seared, and the applesauce is not optional.",
             u: [.fork], m: 1, s: [0], f: [2], h: [.protein], a: [2, 3], w: [.mild, .cold], d: .omnivore, k: true),
        Meal("Texas Brisket", "🥩", "Texas, USA", "Twelve hours of smoke, a black bark, and white bread on the side.",
             u: [.hand, .fork], m: 3, s: [0, 1], f: [1, 2], h: [.protein], a: [3], w: [.mild, .hot], d: .omnivore),
        Meal("Crab Cakes", "🦀", "Maryland, USA", "Mostly crab, barely any filler, browned in butter.",
             u: [.fork], m: 1, s: [0, 1], f: [3], h: [.protein], a: [2], w: [.hot, .mild], d: .omnivore),
        Meal("Sausage and Peppers", "🫑", "Italian-American", "One skillet, sweet peppers, and a roll if you want one.",
             u: [.fork], m: 2, s: [1], f: [1, 2], h: [.protein], a: [3], w: [.mild, .cold], d: .omnivore, k: true),
        Meal("Chicken and Rice Casserole", "🍚", "United States", "The dish that shows up when somebody has a new baby.",
             u: [.fork], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [3], w: [.cold], d: .omnivore, k: true),
        Meal("Red Beans and Rice", "🍚", "Louisiana, USA", "Monday dinner in New Orleans, smoky with andouille.",
             u: [.spoon, .fork], m: 2, s: [1], f: [1, 2], h: [.carbs], a: [3], w: [.cold, .mild], d: .omnivore),
        Meal("Stuffed Shells", "🐚", "Italian-American", "Ricotta piped into pasta, blanketed in sauce and mozzarella.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.carbs], a: [3], w: [.cold], d: .vegetarian, k: true),
        Meal("Loaded Baked Potato", "🥔", "United States", "Butter, sour cream, cheese, chives. A potato doing far too much.",
             u: [.fork], m: 2, s: [0], f: [1, 2], h: [.carbs], a: [2], w: [.cold], d: .vegetarian, k: true),
        Meal("Pasta Primavera", "🥦", "Italian-American", "Spring vegetables, a light cream sauce, and a lot of parmesan.",
             u: [.fork], m: 2, s: [0], f: [2], h: [.vegetable, .carbs], a: [2], w: [.hot, .mild], d: .vegetarian, k: true),
        Meal("Chef Salad", "🥗", "United States", "Ham, turkey, egg and cheese in neat rows over lettuce.",
             u: [.fork], m: 1, s: [0], f: [2], h: [.protein, .vegetable], a: [1], w: [.hot, .mild], d: .omnivore)
        ]
    }
}
